// assets.h - embedded gzipped WebUI (generated by tools/gen_www.sh).
#pragma once
extern const unsigned char index_html_gz[]; extern const unsigned int index_html_gz_len;
extern const unsigned char style_css_gz[];  extern const unsigned int style_css_gz_len;
extern const unsigned char app_js_gz[];     extern const unsigned int app_js_gz_len;
