CORE = gbc

VSRC = c6_fb.v address.v cheat.v clk_test.v dac.v gbc_bridge.v gbc_clk.v main.v mcu_cmd.v msu.v sd_dma.v spi.v sgb.v sgb_cpu.v
VHSRC =

HEADER = config.vh

COMMON_IP = dec_table vram oam hram dac_buf snescmd_buf

XIL_IP =
XIL_IPCORE_DIR =

INT_IP = pll

include ../settings.mk
include ../common.mk
