"""Brazilian Portuguese strings for the sd2snes menu.

Maps const.a65 string labels -> pt-BR text. Accented chars are written as
real UTF-8 here; build_const.py encodes them to the font byte codes.
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
"""

TRANSLATIONS = {
    'text_clkset': 'Ajuste a hora',
    'text_mainmenu': 'Menu Principal',
    'text_mm_file': 'Navegador de Arquivos',
    'text_mm_last': 'Jogos Recentes',
    'text_mm_favorites': 'Jogos Favoritos',
    'mtext_mm_cfg': 'Configurações',
    'mtext_mm_sysinfo': 'Informações do Sistema',
    'mtext_cfg_time': 'Ajustar Relógio',
    'mtext_cfg_bsx': 'Opções BS-X',
    'mtext_cfg_browser': 'Opções do Navegador',
    'mtext_cfg_chip': 'Opções de Chip',
    'mtext_cfg_sgb': 'Opções SGB',
    'mtext_cfg_ingame': 'Opções no Jogo',
    'mtext_cfg_savestates': 'Opções de Savestates',
    'mtext_cfg_scic': 'Opções SuperCIC',
    'mtext_cfg_patch': 'Opções de Patches',
    'mtext_patch_verify': 'Verificar Integridade (aprox. 23s)',
    'mtext_cfg_wifi_en': 'Ativar WiFi',
    'mdesc_cfg_wifi_en': 'Liga/desliga o companion WiFi (desligado: sem ponto de acesso, sem WebUI)',
    'mdesc_cfg_wifi': 'Conectar o sd2snes a uma rede WiFi',
    'wifi_s_scan': 'Procurando redes...',
    'wifi_s_nonet': 'Nenhuma rede encontrada.',
    'wifi_s_hint': 'cima/baixo  A:escolher  X:rescan  B:voltar',
    'wifi_s_curconn': 'Conectado: ',
    'wifi_s_curoff': 'Não conectado',
    'wifi_s_passlbl': 'Senha:',
    'wifi_s_kbd1': 'A:digitar B:apagar X:espaço Y:aA',
    'wifi_s_kbd2': 'START:conectar  SELECT:voltar',
    'wifi_s_connecting': 'Conectando...',
    'wifi_s_ok': 'Conectado!',
    'wifi_s_anykey': 'Aperte qualquer botão para voltar',
    'wifi_s_fail': 'Falhou - confira a senha. A:repetir',
    'mtext_bsx_timesource': 'Relógio BS-X',
    'mtext_bsx_time': 'Hora customizada',
    'mtext_scic_enable': 'Ativar SuperCIC',
    'mtext_scic_vmode_menu': ' {129}Modo vídeo do menu',
    'mtext_scic_vmode_game': ' {129}Modo vídeo do jogo',
    'mtext_browser_sort': 'Ordenar diretórios',
    'mtext_browser_hide_ext': 'Ocultar extensões',
    'mtext_browser_screensaver': 'Protetor de tela',
    'mtext_browser_screensaver_timeout': 'Escurecer tela após',
    'mtext_browser_ledbright': 'Brilho dos LEDs',
    'mtext_ingame_cheats': 'Iniciar com cheats',
    'mtext_ingame_shortreset': 'Reset para o menu',
    'mtext_ingame_enable': 'Hook no jogo',
    'mtext_ingame_buttons': ' {129}Botões no jogo',
    'mtext_ingame_cheat_overlay': ' {129}Menu de cheats',
    'mtext_ingame_holdoff': ' {129}Espera inicial',
    'mtext_ingame_savestate': 'Savestates no jogo',
    'mtext_savestate_slots': ' {129}Slots de savestate',
    'mtext_loadstate_delay': ' {129}Atraso ao carregar',
    'mtext_sgb_enable_hooks': 'Hooks no jogo',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'Recursos do SGB',
    'mtext_sgb_spr_increase': 'Limite máx. sprites (40)',
    'mtext_sgb_volume_boost': 'Boost de volume',
    'mtext_sgb_clock': 'Clock (Timing)',
    'mtext_sgb_bios': 'Versão do BIOS',
    'mtext_ingame_regionpatch': 'Patch auto. de região',
    'mtext_ingame_1chiptransientfixes': 'Correções 1CHIP',
    'mtext_ingame_brightlimit': 'Limite de brilho',
    'mtext_ingame_resetpatch': 'Patch de reset (clock)',
    'mtext_ingame_autosave': 'Auto-salvar',
    'mtext_ingame_autosave_msu1': ' {129}Auto-salvar MSU-1',
    'mtext_chip_cx4_speed': 'Velocidade Cx4',
    'mtext_chip_gsu_speed': 'Velocidade SuperFX',
    'mtext_chip_msu1_volume_boost': 'Boost volume MSU-1',
    'mdesc_mm_last': 'Mostra até 10 jogos recentes',
    'mdesc_mm_favorites': 'Mostra até 20 jogos favoritos',
    'mdesc_mm_cfg': 'Configurar o sd2snes',
    'mdesc_mm_sysinfo': 'Info de FW, SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Ajustar data e hora',
    'mdesc_cfg_bsx': 'Opções específicas BS-X/Satellaview',
    'mdesc_cfg_browser': 'Alterar opções do navegador',
    'mdesc_cfg_chip': 'Recursos especiais de chip',
    'mdesc_cfg_ingame': 'Recursos durante o jogo',
    'mdesc_cfg_sgb': 'Recursos do Super Game Boy',
    'mdesc_cfg_savestates': 'Recursos de savestates',
    'mdesc_cfg_scic': 'Ativar SuperCIC e modos de vídeo',
    'mdesc_cfg_patch': 'Opções de aplicação de patches IPS/BPS',
    'mdesc_patch_verify': 'Relê a ROM aplicada para verificar (carrega bem mais lentamente)',
    'mdesc_bsx_timesource': 'Data/hora vistas pelos jogos BS-X',
    'mdesc_bsx_time': 'Hora e data customizadas para BS-X',
    'mdesc_scic_enable': 'Necessário para recursos SuperCIC',
    'mdesc_scic_vmode_menu': 'Modo de vídeo do menu',
    'mdesc_scic_vmode_game': 'Modo de vídeo dos jogos',
    'mdesc_browser_sort': 'Ordenar listas de arquivos',
    'mdesc_browser_hide_ext': 'Ocultar extensões de arquivos',
    'mdesc_browser_screensaver': 'Escurecer a tela após um tempo',
    'mdesc_browser_screensaver_timeout': 'Tempo para escurecer a tela',
    'mdesc_browser_ledbright': 'Alterar brilho dos LEDs',
    'mdesc_ingame_cheats': 'Iniciar com cheats ativados',
    'mdesc_ingame_shortreset': 'Volta ao menu com reset curto (Des/Lig/Pasta/ROM). Pasta para última pasta. ROM também pré-seleciona a ROM.',
    'mdesc_ingame_enable': 'Necessário para botões e cheats 7E/7F',
    'mdesc_ingame_buttons': 'Botões no jogo (reset, cheats{127}{128}). Requer hook ativo.',
    'mdesc_ingame_cheat_overlay': 'Menu de cheats no jogo (segure L+R+Y+Esq) p/ ligar/desligar ao vivo. Requer hook. Não funciona em chips especiais.',
    'mdesc_ingame_holdoff': 'Espera 10s antes de ativar o hook',
    'mdesc_ingame_savestate': 'Savestates no jogo. Padrão: Salvar Start+R, Carregar Start+L',
    'mdesc_savestate_slots': 'Slots de savestate. Select+Dpad escolhe o slot',
    'mdesc_loadstate_delay': 'Ajustar atraso ao carregar state (frames)',
    'mdesc_sgb_enable_hooks': 'Necessário para botões no jogo',
    'mdesc_sgb_enable_state': 'Savestates internos no SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'Ativar/desativar recursos SGB',
    'mdesc_sgb_spr_increase': 'Aumentar número de sprites visíveis',
    'mdesc_sgb_volume_boost': 'Aumentar volume do áudio SGB',
    'mdesc_sgb_clock': 'Ajustar clock do SGB (timing)',
    'mdesc_sgb_bios': 'Selecionar versão de BIOS do SGB',
    'mdesc_ingame_regionpatch': 'Ignora proteção simples de região',
    'mdesc_ingame_1chiptransientfixes': 'Corrige glitches de brilho em 1CHIP/Jr.',
    'mdesc_ingame_brightlimit': 'Limitar brilho geral (RGB em 1CHIP)',
    'mdesc_ingame_resetpatch': 'Patch de reset para alinhar clocks',
    'mdesc_ingame_autosave': 'Salvar SRM automaticamente quando muda',
    'mdesc_ingame_autosave_msu1': 'MSU-1: salva SRM em pausas. Pode travar.',
    'mdesc_chip_cx4_speed': 'Velocidade do soft core Cx4',
    'mdesc_chip_gsu_speed': 'Velocidade do soft core SuperFX',
    'mdesc_chip_msu1_volume_boost': 'Boost de volume MSU-1 (Rev. E-G)',
    'mdesc_cx4_speed_fast': 'Rodar o mais rápido possível',
    'mdesc_cx4_speed_normal': 'Rodar aprox. na velocidade original',
    'mdesc_gsu_speed_fast': 'Rodar o mais rápido possível',
    'mdesc_gsu_speed_normal': 'Rodar aprox. na velocidade original',
    'text_filesel_selected_file': 'Arquivo selecionado',
    'text_filesel_context_add_to_favorites': 'Adicionar aos favoritos',
    'mdesc_filesel_context_add_to_favorites': 'Adiciona o arquivo aos favoritos',
    'text_filesel_context_remove_from_favorites': 'Remover dos favoritos',
    'mdesc_filesel_context_remove_from_favorites': 'Remove o arquivo dos favoritos',
    'text_recent_context_remove_from_recent': 'Remover dos recentes',
    'mdesc_recent_context_remove_from_recent': 'Remove o arquivo dos jogos recentes',
    'text_filesel_set_as_autoboot': 'Definir como autoboot',
    'mdesc_filesel_set_as_autoboot': 'Inicia esta ROM no próximo power-on (START cancela)',
    'text_filesel_set_as_bgm': 'Definir como música do menu',
    'mdesc_filesel_set_as_bgm': 'Usar este SPC como música de fundo do menu',
    'text_filesel_context_delete_file': 'Deletar',
    'mdesc_filesel_context_delete_file': 'Deleta o arquivo selecionado',
    'text_filesel_context_delete_srm': 'Deletar save',
    'mdesc_filesel_context_delete_srm': 'Deleta o arquivo de save SRM para esta ROM',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': 'Visualizar, ativar ou desativar cheats do arquivo YAML desta ROM',
    'text_cheat_yes': 'Sim',
    'text_cheat_no': 'Não',
    'text_cheat_none_title': 'Cheats',
    'text_cheat_none_msg': 'Nenhum cheat para esta ROM',
    'text_confirm_delete_file': 'Deletar este arquivo?',
    'text_confirm_delete_srm': 'Deletar o arquivo de save?',
    'text_confirm_hint': 'A:Confirmar  B:Cancelar',
    'text_confirm_no_sel': '[Não]',
    'text_confirm_no_unsel': ' Não ',
    'text_confirm_yes_sel': '[Sim]',
    'text_confirm_yes_unsel': ' Sim ',
    'text_statusbar_play': 'A:Jogar B:Voltar X:Menu',
    'text_statusbar_keys': 'A:OK B:Voltar X:Menu Y:Contexto',
    'text_statusbar_spc': 'B:Voltar',
    'text_statusbar_menu': 'A:OK B:Voltar',
    'text_last': 'Jogos recentes',
    'text_favorite': 'Jogos favoritos',
    'text_no_last': 'Nenhum recente',
    'text_no_favorite': 'Nenhum favorito',
    'text_favorites_full': 'Favoritos cheio',
    'text_err_supplfile': 'Arquivo ausente:',
    'text_err_noimpl': 'Chip não suportado:',
    'text_err_generic': 'Erro ao carregar:',
    'text_on_p1': 'Lig: P1',
    'text_on_p2': 'Lig: P2',
    'text_on': 'Lig',
    'text_off': 'Des',
    'text_cover_large': 'Grande',
    'text_cover_small': 'Pequeno',
    'text_nav_folder': 'Pasta',
    'text_nav_rom': 'ROM',
    'text_enabled': 'Ativado',
    'text_disabled': 'Desativ.',
    'text_normal': 'Normal',
    'text_fast': 'Rápido',
    'text_rtc': 'Tempo real',
    'text_custom': 'Custom.',
    'text_yes': 'Sim',
    'text_no': 'Não',
    'text_auto': 'Auto',
    'text_add': 'Adicionar',
    'text_remove': 'Remover',
    'text_edit': 'Editar',
    'text_save': 'Salvar',
    'text_1min': '1 min',
    'text_2min': '2 mins',
    'text_3min': '3 mins',
    'text_4min': '4 mins',
    'text_5min': '5 mins',
    'text_10min': '10 mins',
    'text_15min': '15 mins',
    'text_20min': '20 mins',
    'text_30min': '30 mins',
    'text_45min': '45 mins',
    'text_60min': '1 hora',
    'text_spcplay': 'Tocador de SPC',
    'text_spcload': 'Carregando SPC no SPC700{127}{128}  ',
    'text_spcstarta': '**** Tocando SPC ****',
    'text_spcstartb': 'Nome:  ',
    'text_spcstartc': 'Música:',
    'text_spcstartd': 'Artista:',
    'text_spc_statusbar': 'B:Voltar',
    'text_loading': 'Carregando{127}{128}                     ',
    'text_saving': 'Salvando{127}{128}                       ',
    'text_cheat': 'Cheats para ',
    'text_ips_nopatch': '[Sem patch]',
    'text_ips_header': 'Patches',
    'cheat_tab_head': 'Nome                                     Ativado',
    'cheat_tab_hint_text': ' A:Habi./Desab.   B:Salvar & Sair ',
    'mtext_browser_showcov': 'Mostrar capas',
    'mdesc_browser_showcov': 'Exibir capas dos jogos no menu',
    'mtext_browser_covlists': ' {129}Favoritos/Recentes',
    'mdesc_browser_covlists': 'Exibir capas também nas listas Recentes e Favoritos',
    'mtext_browser_menumusic': 'Música do menu',
    'mtext_browser_menusfx': 'Sons do menu',
    'mdesc_browser_menumusic': 'Tocar música de fundo (menu.spc) no menu',
    'mtext_browser_sortfav': 'Ordenar favoritos',
    'mdesc_browser_sortfav': 'Ordena a lista de favoritos em ordem alfabética',
    'mtext_browser_restoretheme': 'Restaurar tema',
    'mdesc_browser_restoretheme': 'Voltar o tema do menu para o padrão de fábrica',
    'mtext_browser_restoremusic': 'Restaurar música',
    'mdesc_browser_restoremusic': 'Voltar a música do menu para o padrão (menu.spc)',
    'text_mm_language': 'Idioma',
    'mdesc_mm_language': 'Define o idioma do menu/firmware',
    'mdesc_browser_menusfx': 'Tocar efeitos sonoros ao navegar pelo menu',
    'mtext_browser_gameinfo': 'Ficha de Jogo',
    'mdesc_browser_gameinfo': 'Mostra capa, screenshot e infos antes de iniciar uma ROM que tenha uma entrada em /sd2snes/info',
    'mtext_browser_gameinfo_video': ' {129}Exibir vídeo',
    'mdesc_browser_gameinfo_video': 'Reproduz o clipe animado na Ficha de Jogo (desligado mostra um snapshot estático)',
    'mtext_browser_gameinfo_music': ' {129}Tocar música do vídeo',
    'mdesc_browser_gameinfo_music': 'Toca a trilha do vídeo enquanto o clipe aparece. Requer Exibir vídeo.',
    'text_gi_developer': 'Produtora',
    'text_gi_year': 'Ano',
    'text_gi_players': 'Jogadores',
    'text_gi_genre': 'Gênero',
    'text_gi_chip': 'Chip',
    'text_gi_footer': 'A: Jogar  B: Voltar  Y: Descrição',
    'text_gi_footer_nav': 'A:Jogar B:Voltar Y:Desc Cima/Baixo:Jogo',
    'text_gi_footer_full': 'B: Voltar  Cima/Baixo: Rolar',
}
