"""Japanese strings for the sd2snes menu (日本語).

CJK characters are drawn from the glyph cache in VRAM (snes/cjk.a65): build_const.py moves
this whole column, with its glyphs, into lang_ja.bin, which the menu loads into WRAM
when the language is selected. Any label left out falls back to English.
"""

TRANSLATIONS = {
    'text_clkset': '時刻を設定してください',
    'text_mainmenu': 'メインメニュー',
    'text_mm_file': 'ファイルブラウザー',
    'text_mm_last': '最近遊んだゲーム',
    'text_mm_favorites': 'お気に入り',
    'text_igm_hdr_controls': 'ゲーム中のショートカット',
    'text_igm_open': 'このメニューを開く',
    'text_igm_save': 'ステートセーブ',
    'text_igm_load': 'ステートロード',
    'text_igm_slot': 'スロットを選択',
    'text_igm_reset_game': 'ゲームをリセット',
    'text_igm_reset': 'メニューに戻る',
    'text_igm_cheats_on': 'チートをONにする',
    'text_igm_cheats_off': 'チートをOFFにする',
    'text_igm_hooks_off': 'フックを無効化',
    'text_igm_hooks_10s': 'フックを10秒間無効化',
    'text_igm_pergame': '* このゲーム専用のボタン設定 (savestate_inputs.yml)',
    'text_igm_hdr_keys': 'メニューの操作',
    'text_igm_keys1': '左右: タブ   L/R: 先頭/末尾   A: 開く',
    'text_igm_keys2': 'B: 戻る   START: 閉じる   SELECT: このヘルプ',
    'text_igm_unavail': 'このゲームでは使用できません',
    'text_igm_key_up': '上',
    'text_igm_key_down': '下',
    'text_igm_key_left': '左',
    'text_igm_key_right': '右',
    'text_igm_st_title': 'ステートスロットを選択',
    'text_igm_st_slot': 'スロット',
    'text_igm_st_full': '使用中',
    'text_igm_st_empty': '空き',
    'text_igm_st_hint_save': 'セーブ',
    'text_igm_st_disabled': 'ステートスロットは無効です',
    'text_igm_st_hint_load': 'ロード',
    'text_igm_st_unavail': 'このゲームではステートセーブを使用できません',
    'text_igm_tab_cheats': 'チート',
    'text_igm_tab_states': 'ステート',
    'text_igm_tab_saves': 'セーブ',
    'text_igm_tab_help': 'ヘルプ',
    'text_igm_tab_manual': 'ガイド',
    'text_igm_tab_trainer': 'トレーナー',
    'text_igm_sv_title': 'セーブデータ',
    'text_igm_sv_nosram': 'このゲームにはバッテリーバックアップがありません',
    'text_igm_sv_file': '.srmファイル:',
    'text_igm_sv_exists': 'あり',
    'text_igm_sv_missing': 'なし',
    'text_igm_sv_size': 'サイズ:',
    'text_igm_sv_write': '最終更新:',
    'text_igm_sv_autosave': 'オートセーブ:',
    'text_igm_sv_on': 'ON',
    'text_igm_sv_off': 'OFF',
    'text_igm_sv_hint_on': 'プレイ中に自動でセーブされます',
    'text_igm_sv_hint_off': 'オートセーブOFF - ゲーム内でセーブしてください',
    'text_igm_sv_slottitle': 'SRAMスロットを選択',
    'text_igm_sv_slot': 'スロット',
    'text_igm_sv_slothint': '次にゲームを起動したときに反映されます',
    'text_igm_mn_title': '取扱説明書',
    'text_igm_mn_read': 'A: 説明書を読む',
    'text_igm_mn_pages': 'ページ',
    'text_igm_mn_notfound': '説明書が見つかりません',
    'text_igm_mn_error': '説明書を読み込めませんでした',
    'text_igm_mn_guide': 'ガイド',
    'text_igm_mn_select': 'ガイドを選択',
    'text_igm_mn_keys1': 'A: 2倍表示   L/R: ページ送り',
    'text_igm_mn_keys2': '十字キー: スクロール   B: 戻る',
    'text_igm_mn_slug_manual': '説明書',
    'text_igm_mn_slug_guide': '攻略',
    'text_igm_mn_slug_map': 'マップ',
    'text_igm_mn_slug_insert': '付録',
    'text_igm_mn_slug_other': 'その他',
    'text_igm_tr_title': 'RAMトレーナー',
    'text_igm_tr_searchtype': '検索方法:',
    'text_igm_tr_datatype': 'データ型:',
    'text_igm_tr_value': '値:',
    'text_igm_tr_candidates': '候補数:',
    'text_igm_tr_compare': '比較:',
    'text_igm_tr_exact': '値を指定',
    'text_igm_tr_unknown': '不明な値',
    'text_igm_tr_8bit': '8ビット',
    'text_igm_tr_16bit': '16ビット',
    'text_igm_tr_eq': '等しい',
    'text_igm_tr_ne': '等しくない',
    'text_igm_tr_changed': '変化あり',
    'text_igm_tr_unchanged': '変化なし',
    'text_igm_tr_increased': '増えた',
    'text_igm_tr_decreased': '減った',
    'text_igm_tr_gt': 'より大きい',
    'text_igm_tr_lt': 'より小さい',
    'text_igm_tr_newsearch': '新規検索',
    'text_igm_tr_filter': '絞り込み',
    'text_igm_tr_results': '検索結果',
    'text_igm_tr_reset': '検索をリセット',
    'text_igm_tr_address': 'アドレス',
    'text_igm_tr_current': '現在値',
    'text_igm_tr_setvalue': '値を書き込む',
    'text_igm_tr_freeze': '固定',
    'text_igm_tr_unfreeze': '固定解除',
    'text_igm_tr_savecheat': 'チートとして保存',
    'text_igm_tr_frozen': '固定中',
    'text_igm_tr_searching': '検索中...',
    'text_igm_tr_noresults': '候補がなくなりました',
    'text_igm_tr_toomany': '候補が多すぎます - さらに絞り込んでください',
    'text_igm_tr_dropped_rst': '本体のリセットにより検索をリセットしました',
    'text_igm_tr_nofreeze': '固定できる値は4つまでです',
    'text_igm_tr_hint_setup': 'A: 選択   十字キー: 変更',
    'text_igm_tr_hint_edit': '十字キー: 編集   A: 決定   B: キャンセル',
    'text_igm_tr_hint_list': 'A: 詳細   B: 戻る',
    'text_igm_tr_master_off': 'チート全体がOFFです',
    'text_igm_tr_saved': 'チートを保存しました',
    'text_igm_tr_savefail': 'チートを保存できませんでした',
    'text_igm_tr_unpin': 'リストから外す',
    'mtext_mm_cfg': '設定',
    'mtext_mm_sysinfo': 'システム情報',
    'mtext_cfg_time': '時計の設定',
    'mtext_cfg_ask_clock': '起動時に時刻を入力',
    'mtext_cfg_boot_intro': '起動画面',
    'mtext_cfg_warn_exp': '試験的コアの警告',
    'mtext_cfg_bsx': 'BS-Xの設定',
    'mtext_cfg_browser': 'ブラウザーの設定',
    'mtext_cfg_chip': '特殊チップの設定',
    'mtext_cfg_sgb': 'SGBの設定',
    'mtext_cfg_ingame': 'ゲーム中の設定',
    'mtext_cfg_savestates': 'ステートセーブの設定',
    'mtext_cfg_scic': 'SuperCICの設定',
    'mtext_cfg_tour': '新機能の紹介',
    'mtext_bsx_timesource': 'BS-Xの時計',
    'mtext_bsx_time': '任意の日時',
    'mtext_scic_enable': 'SuperCICを有効化',
    'mtext_scic_vmode_menu': ' {129}メニューの映像モード',
    'mtext_scic_vmode_game': ' {129}ゲームの映像モード',
    'mtext_scic_buscompat': 'バスタイミング互換',
    'mtext_browser_sort': 'ファイル一覧を並べ替え',
    'mtext_browser_hide_ext': '拡張子を非表示',
    'mtext_browser_msu_folders': 'MSU-1フォルダーをゲームとして開く',
    'mtext_browser_sd2snes_dir': 'sd2snesフォルダーを表示',
    'mtext_browser_screensaver': 'スクリーンセーバー',
    'mtext_browser_screensaver_timeout': '画面を暗くするまで',
    'mtext_browser_ledbright': 'LEDの明るさ',
    'mtext_ingame_cheats': 'チートONで開始',
    'mtext_ingame_shortreset': 'リセットでメニューに戻る',
    'mtext_ingame_enable': 'ゲーム中フック',
    'mtext_ingame_pad2': ' {129}2Pコントローラーでも操作',
    'mtext_ingame_buttons': ' {129}ゲーム中のボタン操作',
    'mtext_ingame_cheat_overlay': ' {129}ゲーム中メニュー',
    'mtext_ingame_holdoff': ' {129}フックの開始を遅らせる',
    'mtext_ingame_savestate': 'ゲーム中のステートセーブ',
    'mtext_savestate_slots': ' {129}ステートスロット',
    'mtext_loadstate_delay': ' {129}ステートロードの待ち時間 (フレーム)',
    'mtext_sgb_enable_hooks': 'ゲーム中フック',
    'mtext_sgb_enable_state': 'ステートセーブ (XR, XL)',
    'mtext_sgb_enh_override': 'SGB拡張機能',
    'mtext_sgb_spr_increase': 'スプライト上限の拡張 (40)',
    'mtext_sgb_volume_boost': '音量ブースト',
    'mtext_sgb_clock': 'クロック (タイミング)',
    'mtext_sgb_bios': 'BIOSのバージョン',
    'mtext_gbc_mode': 'Game Boy Colorモード',
    'mtext_gbc_sync': 'Game Boy Colorの同期',
    'mtext_gbc_stretch': 'Game Boy Colorの拡大表示',
    'mtext_ingame_regionpatch': 'リージョン自動パッチ',
    'mtext_ingame_1chiptransientfixes': '1CHIPの過渡現象対策',
    'mtext_ingame_brightlimit': '明るさの上限',
    'mtext_ingame_resetpatch': 'クロック位相のリセットパッチ',
    'mtext_ingame_autosave': 'オートセーブ',
    'mtext_ingame_autosave_msu1': ' {129}MSU-1のオートセーブ',
    'mtext_chip_cx4_speed': 'Cx4の速度',
    'mtext_chip_cc_time_limit': '競技用カートの制限時間 (分)',
    'mtext_chip_gsu_speed': 'SuperFXの速度',
    'mtext_chip_msu1_volume_boost': 'MSU-1の音量ブースト',
    'mtext_a26_width': 'Atari 2600の画面幅',
    'mdesc_mm_last': '最近遊んだゲームを最大10本表示します',
    'mdesc_mm_favorites': 'お気に入りのゲームを最大20本表示します',
    'mdesc_mm_cfg': 'sd2snesの設定を変更します',
    'mdesc_mm_sysinfo': 'ファームウェア、SDカード、SNES、CIC{127}{128}の情報を表示します',
    'mdesc_cfg_time': '日付と時刻を設定します',
    'mdesc_cfg_ask_clock': '時計が未設定のとき、起動時に時刻の入力を求めます',
    'mdesc_cfg_boot_intro': '電源を入れたとき、効果音付きのオープニング画面を表示します',
    'mdesc_cfg_warn_exp': '試験的なコア (NES、Master System、Atari 2600、Game Boy Color) でゲームを起動する前に確認します',
    'mdesc_cfg_bsx': 'BS-X/Satellaview専用の設定です',
    'mdesc_cfg_browser': 'ファイルブラウザーの設定を変更します',
    'mdesc_cfg_chip': '特殊チップの機能を設定します',
    'mdesc_cfg_ingame': 'ゲーム中に使う機能を設定します',
    'mdesc_cfg_sgb': 'Super Game Boyの機能を設定します',
    'mdesc_cfg_savestates': 'ステートセーブの機能を設定します',
    'mdesc_cfg_scic': 'SuperCICの有効/無効と映像モードを設定します',
    'mdesc_cfg_tour': '初回起動時に表示された新機能の紹介をもう一度表示します',
    'mdesc_bsx_timesource': 'BS-Xのゲームに渡す日時を選びます',
    'mdesc_bsx_time': 'BS-Xのゲーム用に任意の日時を設定します',
    'mdesc_scic_enable': 'SuperCICの拡張機能を使うのに必要です',
    'mdesc_scic_vmode_menu': 'メニューの映像モードを設定します',
    'mdesc_scic_vmode_game': 'ゲームの映像モードを設定します',
    'mdesc_scic_buscompat': '一部のゲームが固まったり表示が乱れたりする本体向けに、カートのバスタイミングを狭めます。この本体でフリーズするときだけONにしてください。',
    'mdesc_browser_sort': 'ファイル一覧を並べ替えるかどうかを選びます',
    'mdesc_browser_hide_ext': '拡張子を隠すかどうかを選びます',
    'mdesc_browser_msu_folders': 'MSU-1のROMが1本だけ入ったフォルダーでAを押すと、そのゲームを起動します',
    'mdesc_browser_sd2snes_dir': 'ファイル一覧に/sd2snesを表示します',
    'mdesc_browser_screensaver': '一定時間操作がないと画面を暗くします',
    'mdesc_browser_screensaver_timeout': '画面を暗くするまでの時間を設定します',
    'mdesc_browser_ledbright': 'LEDの明るさを変更します',
    'mdesc_ingame_cheats': 'ゲーム開始時にチートをONにするかどうかを選びます。ゲーム中のボタン操作でも切り替えられます',
    'mdesc_ingame_shortreset': 'リセット時の戻り先です。フォルダー/ROM: 前回のゲームのフォルダーを開きます。長押し判定: 短押しでゲームをリセット、長押しでROMと同じ動作。',
    'mdesc_ingame_enable': 'ゲーム中メニュー、ステートセーブ、ゲーム中のボタン操作、メモリーを書き換えるチートに必要です',
    'mdesc_ingame_pad2': '2Pコントローラーからのボタン操作も受け付けます。割り込みごとの処理が少し増えます。',
    'mdesc_ingame_buttons': 'ゲーム中のボタン操作 (リセット、チートの切り替え{127}{128}) を有効にします。ゲーム中フックが必要です。',
    'mdesc_ingame_cheat_overlay': 'ゲーム中メニュー (L+R+Y+左を長押し) でチート、ステート、セーブ、ガイドを使えます。ゲーム中フックが必要です。一部の特殊チップのゲームでは使用できません。',
    'mdesc_ingame_holdoff': 'フックを有効にするまで10秒待ちます (フック有効で起動しないゲーム向け)',
    'mdesc_ingame_savestate': 'ゲーム中のステートセーブを有効にし、使うコントローラーを選びます。初期設定: セーブ Start+R / ロード Start+L',
    'mdesc_savestate_slots': 'ステートスロットを有効にします。Select+十字キーの各方向でスロットを選びます',
    'mdesc_loadstate_delay': 'ステートロードの待ち時間 (フレーム) を調整します',
    'mdesc_sgb_enable_hooks': 'ゲーム中のボタン操作に必要です',
    'mdesc_sgb_enable_state': 'SGB2内蔵のステートセーブを有効にします (XR, XL)',
    'mdesc_sgb_enh_override': 'SGBの拡張機能を有効/無効にします',
    'mdesc_sgb_spr_increase': '同時に表示できるスプライトの数を増やします',
    'mdesc_sgb_volume_boost': 'SGBの音が小さすぎる場合に音量を上げます',
    'mdesc_sgb_clock': 'SGBのクロック (タイミング) を調整します',
    'mdesc_sgb_bios': 'SGBのファームウェア/BIOSのバージョンを選びます',
    'mdesc_gbc_mode': 'Game Boyのゲームに使うコア (SGBまたはGBC) を選びます。Mk.IIIのみ',
    'mdesc_gbc_sync': 'Genlock: なめらか。等速: 実機と同じ速度、コマ落ちする場合あり。Mk.IIIのみ',
    'mdesc_gbc_stretch': 'ハイカラー画面を256x192に広げます。Mk.IIIのみ',
    'mdesc_ingame_regionpatch': 'ゲームの簡易的なリージョンチェックを回避します',
    'mdesc_ingame_1chiptransientfixes': '明るさの変化にパッチを当て、1CHIP/Jr.本体での同期の乱れ、走査線のかすれ、影の欠けを直します',
    'mdesc_ingame_brightlimit': '全体の明るさを制限します (1CHIP本体でRGBの信号レベルに合わせる場合など)',
    'mdesc_ingame_resetpatch': 'リセットパッチでクロックを合わせます。一部のゲームの表示不具合を直します',
    'mdesc_ingame_autosave': 'セーブRAMの内容が変わると.srmファイルを自動で保存します',
    'mdesc_ingame_autosave_msu1': 'MSU-1: 可能なタイミングで.srmファイルを自動保存します。一瞬カクつくことがあります。',
    'mdesc_chip_cx4_speed': 'Cx4ソフトコアの速度を設定します',
    'mdesc_chip_cc_time_limit': "Campus Challenge '92 / PowerFest '94 のラウンドの制限時間を設定します",
    'mdesc_chip_gsu_speed': 'SuperFXソフトコアの速度を設定します',
    'mdesc_chip_msu1_volume_boost': 'sd2snesのMSU-1の音が小さすぎる場合に音量を上げます (Rev. E-G)',
    'mdesc_a26_width': 'Atari 2600の画面幅: 160は等倍 (1:1)、256は画面いっぱいに表示します',
    'mdesc_cx4_speed_fast': 'できるだけ高速で動作します',
    'mdesc_cx4_speed_normal': '実機に近い速度で動作します',
    'mdesc_gsu_speed_fast': 'できるだけ高速で動作します',
    'mdesc_gsu_speed_normal': '実機に近い速度で動作します',
    'text_filesel_selected_file': '選択中のファイル',
    'text_filesel_context_add_to_favorites': 'お気に入りに追加',
    'mdesc_filesel_context_add_to_favorites': '選択中のファイルをお気に入りに追加します',
    'text_filesel_context_remove_from_favorites': 'お気に入りから削除',
    'mdesc_filesel_context_remove_from_favorites': '選択中のファイルをお気に入りから削除します',
    'text_recent_context_remove_from_recent': '最近遊んだゲームから削除',
    'mdesc_recent_context_remove_from_recent': '選択中のファイルを最近遊んだゲームの一覧から削除します',
    'text_filesel_set_as_autoboot': '自動起動に設定',
    'mdesc_filesel_set_as_autoboot': '次回の電源投入時にこのROMを自動で起動します (電源投入/リセット時にSTARTを押し続けると中止)',
    'text_filesel_set_as_bgm': 'メニューBGMに設定',
    'mdesc_filesel_set_as_bgm': 'このSPCをメニューのBGMにします',
    'text_filesel_context_delete_file': '削除',
    'mdesc_filesel_context_delete_file': '選択中のファイルを削除します',
    'text_filesel_context_delete_srm': 'セーブデータを削除',
    'mdesc_filesel_context_delete_srm': 'このROMのセーブデータ (.srm) を削除します',
    'text_filesel_context_cheats': 'チート',
    'mdesc_filesel_context_cheats': 'このROMのYAMLファイルにあるチートを表示し、ON/OFFを切り替えます',
    'text_filesel_context_gameinfo': 'ゲーム情報',
    'mdesc_filesel_context_gameinfo': 'プレイ前にこのROMの情報画面 (パッケージ画像、画面写真、詳細) を表示します',
    'text_cheat_yes': 'ON  ',
    'text_cheat_no': 'OFF ',
    'text_cheat_none_title': 'チート',
    'text_ce_name': '名前',
    'text_cheat_none_msg': 'このROMのチートはありません',
    'text_confirm_delete_file': 'このファイルを削除しますか？',
    'text_confirm_delete_srm': 'セーブデータを削除しますか？',
    'text_confirm_hint': 'A:決定  B:キャンセル',
    'text_confirm_no_sel': '[いいえ]',
    'text_confirm_no_unsel': ' いいえ ',
    'text_confirm_yes_sel': '[はい]',
    'text_confirm_yes_unsel': ' はい ',
    'text_statusbar_play': 'A:プレイ B:戻る X:メニュー',
    'text_statusbar_keys': 'A:選択 B:戻る X:メニュー Y:その他',
    'text_statusbar_spc': 'B:戻る',
    'text_statusbar_menu': 'A:選択 B:戻る',
    'text_last': '最近遊んだゲーム',
    'text_favorite': 'お気に入り',
    'text_no_last': '最近遊んだゲームなし',
    'text_no_favorite': 'お気に入りなし',
    'text_favorites_full': 'お気に入りがいっぱいです',
    'text_err_supplfile': '必須ファイルがありません:',
    'text_err_noimpl': '未対応のチップ:',
    'text_err_nohw': 'Mk.IIIが必要です:',
    'text_err_generic': '読み込みエラー:',
    'text_exp_title': '*試験的*なコア',
    'text_exp_l1': 'このコアはまだ開発中です:',
    'text_exp_l2': '- 動作が遅かったり、音や画面が',
    'text_exp_l3': '  乱れたりすることがあります',
    'text_exp_l4': '- 動かないゲームもあります',
    'text_exp_l5': '- ステートセーブとゲーム中メニューは',
    'text_exp_l6': '  まだ使用できません',
    'text_exp_start': '開始',
    'text_exp_back': '戻る',
    'text_exp_nowarn': '開始して今後は警告しない',
    'text_on_p1': 'ON: 1P',
    'text_on_p2': 'ON: 2P',
    'text_on': 'ON',
    'text_off': 'OFF',
    'text_15_max': '15 (最大)',
    'text_theme': 'テーマ',
    'text_cover_large': '大',
    'text_cover_small': '小',
    'text_gameinfo_context': 'Yメニュー',
    'text_nav_folder': 'フォルダー',
    'text_nav_rom': 'ROM',
    'text_nav_duration': '長押し判定',
    'text_enabled': '有効',
    'text_disabled': '無効',
    'text_normal': '標準',
    'text_fast': '高速',
    'text_a26_w256': '256 (ワイド)',
    'text_rtc': '現在時刻',
    'text_custom': '任意',
    'text_yes': 'はい',
    'text_no': 'いいえ',
    'text_onbg_question': '新機能の紹介を見ますか？',
    'text_onbg_lang': '言語:',
    'text_onbg_hint': '(A) はい        (B) いいえ',
    'text_auto': '自動',
    'text_gbc_prefer_sgb': 'SGB優先',
    'text_gbc_prefer_gbc': 'GBC優先',
    'text_gbc_genlock': 'Genlock',
    'text_gbc_exact': '等速',
    'text_add': '追加',
    'text_remove': '削除',
    'text_edit': '編集',
    'text_save': '保存',
    'text_1min': '1分',
    'text_2min': '2分',
    'text_3min': '3分',
    'text_4min': '4分',
    'text_5min': '5分',
    'text_10min': '10分',
    'text_15min': '15分',
    'text_20min': '20分',
    'text_30min': '30分',
    'text_45min': '45分',
    'text_60min': '1時間',
    'text_spcplay': 'SPCミュージックプレーヤー',
    'text_spcload': 'SPC700にSPCデータを転送中{127}{128}',
    'text_spcstarta': '**** SPCを再生中 ****',
    'text_spcstartb': 'ゲーム',
    'text_spcstartc': '曲名  ',
    'text_spcstartd': '作曲者',
    'text_spc_statusbar': 'B:戻る',
    'text_loading': '読み込み中{127}{128}                    ',
    'text_saving': '保存中{127}{128}                        ',
    'text_cheat': 'チート: ',
    'text_cheat_noname': '(名前なし)',
    'text_igm_cheat_noname': '(名前なし)',
    'text_igm_cheat_on': 'ON',
    'text_igm_cheat_off': 'OFF',
    'text_igm_ch_none': 'チートはありません',
    'text_igm_ft_tab': '<>:タブ L/R:端 A:開く SEL:ヘルプ B:閉じる',
    'text_igm_ft_cheats': 'A:ON/OFF Y:編集 SEL:追加 X:チート B:戻る',
    'text_igm_ft_generic': 'A:選択 B:戻る',
    'text_igm_master_on': 'チート: ON',
    'text_igm_master_off': 'チート: OFF',
    'text_igm_ft_ce_edit': 'A:編集 SEL:コード追加 Y:削除 B:戻る',
    'text_igm_ft_ce_kbd': 'A:入力 Y:消す SEL:空白 X:決定 B:キャンセル',
    'text_igm_ft_help': 'B:戻る START:閉じる',
    'text_igm_ce_title_new': '新しいチート',
    'text_igm_ce_title_edit': 'チートを編集',
    'text_igm_ce_name': '名前:',
    'text_igm_ce_save': '保存',
    'text_igm_ce_delete': 'チートを削除',
    'text_igm_ce_confirm': 'このチートを削除しますか？',
    'text_igm_ce_confirm_keys': 'A: はい   B: いいえ',
    'text_igm_ce_nosup': 'ファームウェアを更新してください',
    'text_igm_ce_full': 'チートの一覧がいっぱいです',
    'text_igm_ce_badcode': '無効なコードです',
    'text_si_fw': '    ファームウェア: {2}',
    'text_si_busy': '空き容量を計算中{127}{128}',
    'text_si_removed': '    *** SDカード未挿入/USB使用中 ***',
    'text_si_maker': 'SDメーカー/OEM:  0x{3}, {34}{4}{34}',
    'text_si_product': 'SD製品名:        {34}{5}{34}, Rev. {6}.{7}',
    'text_si_serial': 'SDシリアル番号:  {8}, 製造 {9}/{10}',
    'text_si_acc': 'SDアクセス: {11}.{12} / {13}.{14} ms 平均/最大',
    'text_si_accmeas': 'SDアクセス: 測定中{127}{128}',
    'text_si_usage': 'カード使用量: {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': '確認中{127}{128}',
    'text_si_sgb_missing': 'なし',
    'text_si_sgb_mismatch': '不一致',
    'text_si_sgb_ok': 'OK',
    'text_si_cic': 'CICの状態: {19}',
    'text_si_clk': 'SNESマスタークロック: {20}Hz',
    'text_si_clkmeas': 'SNESマスタークロック: 測定中{127}{128}',
    'text_si_u16on': 'Ultra16 シリアル番号 {21} (自動起動ON)',
    'text_si_u16off': 'Ultra16 シリアル番号 {21} (自動起動OFF)',
    'text_si_model': '機種: {22}',
    'text_si_updatefw': '** ファームウェアを更新してください **',
    'mtext_mm_memtest': 'メモリーテスト',
    'mdesc_mm_memtest': 'FPGAとRAMの配線を確認したあと、すべてのメモリーセルを検査します (30秒)。本体はリセットされます。',
    'text_mtl_prompt': 'A: テスト開始  B: 閉じる',
    'text_mtl_prompt2': '本体がリセットされます (約30秒)',
    'text_mtl_run': 'メモリーテスト中です。お待ちください{127}{128}',
    'text_mtl_none': 'まだテストを実行していません。',
    'text_mtl_pass': 'RAMの信号線はすべて正常です。',
    'text_mtl_fail': '異常が見つかりました:',
    'text_mtl_nocore': '/sd2snes/fpga_test がないか破損',
    'text_mtl_more': '(ほかの異常は省略)',
    'text_mtl_cellpass': 'すべてのセルが正常です。',
    'text_mtl_cellfail': '最初の不良セル: 0x',
    'text_mtl_cellskip': 'セル検査を省略 (先に配線を修理)',
    'text_mt_data': '要確認: データ線D',
    'text_mt_addr': '要確認: アドレス線A',
    'text_mt_short': '短絡の可能性: A',
    'text_mt_bytesel': '要確認: LB# / UB#',
    'text_mt_ctrl': '要確認: CE# / OE# / WE#',
    'text_mt_fpgactrl': '要確認: FPGAのCE# / OE# / WE#',
    'text_pcm_title': 'PCMプレーヤー',
    'text_pcm_prompt': 'A: 再生/一時停止   B: 閉じる',
    'text_pcm_promptb': 'B: 閉じる',
    'text_pcm_paused': '一時停止中',
    'text_pcm_erropen': 'このファイルを読み込めません。',
    'text_pcm_errmagic': 'MSU-1のPCMファイルではありません。',
    'text_pcm_nosup': '** ファームウェアを更新してください **',
    'text_st_slotb_title': 'Sufami Turbo - スロットB',
    'text_st_slotb_footer': 'A:プレイ  B:戻る  <>:ページ  LR:端',
    'text_st_slotb_none': '[スロットBにカートなし]',
    'text_ips_nopatch': '[パッチなし]',
    'text_ips_header': 'パッチ',
    'text_patch_hdr_auto': '自動 ',
    'text_patch_hdr_on': 'あり ',
    'text_patch_hdr_off': 'なし ',
    'text_patch_footer': 'A:プレイ  Y:その他  B:戻る  <>:ページ  LR:端',
    'text_patch_creating': 'パッチ済みROMを作成中...',
    'text_err_patchexport': 'パッチ済みROMの書込失敗',
    'text_patch_export_ok': 'パッチ済みROMを作成しました',
    'text_patch_export_part': 'ROMはOK、付属データは不完全',
    'text_patch_export_exists': 'パッチ済みROMはすでにあります',
    'text_patch_hdrsel_auto': '自動 (判別)',
    'text_patch_hdrsel_on': 'ヘッダーあり',
    'text_patch_hdrsel_off': 'ヘッダーなし',
    'mtext_patch_header_mode': 'ヘッダーモード',
    'mdesc_patch_header_mode': 'IPSのオフセットの扱いを選びます: 自動、ヘッダーあり (512バイトずらす)、ヘッダーなし。',
    'mtext_patch_create_rom': 'パッチ済みROMを作成',
    'mdesc_patch_create_rom': 'パッチ済みROMを元のROMの隣にパッチと同じ名前で書き出し、パッケージ画像、セーブ、チート、ガイドもコピーします。数分かかります。',
    'cheat_tab_head': '内容                                    有効',
    'cheat_tab_hint_text': ' A:ON/OFF  Y:編集  Sel:追加  B:閉じる',
    'mtext_browser_showcov': 'パッケージ画像を表示',
    'mdesc_browser_showcov': 'メニューにゲームのパッケージ画像を表示します',
    'mtext_browser_covlists': ' {129}お気に入り/最近遊んだゲーム',
    'mdesc_browser_covlists': '最近遊んだゲームとお気に入りの一覧にもパッケージ画像を表示します',
    'mtext_browser_menumusic': 'メニューBGM',
    'mtext_browser_menumusic_random': ' {129}ランダム再生',
    'mtext_browser_menusfx': 'メニューの効果音',
    'mtext_browser_text_outline': '文字の縁取り',
    'mtext_browser_text_aa': '文字のアンチエイリアス',
    'mdesc_browser_menumusic': 'メニューでBGM (menu.spc) を再生します',
    'mtext_browser_sortfav': 'お気に入りを並べ替え',
    'mdesc_browser_sortfav': 'お気に入りの一覧を名前順に並べ替えます',
    'mtext_browser_restoretheme': 'テーマを元に戻す',
    'mdesc_browser_restoretheme': 'メニューのテーマを内蔵の標準テーマに戻します',
    'mtext_browser_restoreclassic': 'クラシックテーマに戻す',
    'mdesc_browser_restoreclassic': '従来のsd2snesの見た目を読み込みます (カードに/sd2snes/classic.thmが必要です)',
    'mtext_browser_restoremusic': 'BGMを元に戻す',
    'mdesc_browser_restoremusic': 'メニューのBGMを標準 (menu.spc) に戻します',
    'mdesc_browser_menumusic_random': '読み込むたびに音楽フォルダーから.spcをランダムに選びます',
    'mdesc_browser_text_outline': 'メニューの文字の暗い縁取り: テーマに従うか、強制的にON/OFFにします',
    'mdesc_browser_text_aa': 'メニューの文字の輪郭のなめらかさ: テーマに従うか、強制的にON/OFFにします',
    'text_mm_language': '言語',
    'mdesc_mm_language': 'メニュー/ファームウェアの表示言語を設定します',
    'mdesc_browser_menusfx': 'メニュー操作時に効果音を鳴らします',
    'mtext_browser_gameinfo': 'ゲーム情報',
    'mtext_gameinfo_enable': '情報画面を表示',
    'mdesc_browser_gameinfo': '/sd2snes/infoに情報があるROMは、起動前にパッケージ画像、画面写真、詳細を表示します',
    'mdesc_cfg_gameinfo': '起動前に表示するゲーム情報画面の設定です',
    'mtext_browser_gameinfo_video': ' {129}動画を表示',
    'mdesc_browser_gameinfo_video': 'ゲーム情報画面で動画を再生します (OFFのときは静止画を表示)',
    'mtext_browser_gameinfo_music': ' {129}動画の音声を再生',
    'mdesc_browser_gameinfo_music': '動画の表示中にその音声を再生します。「動画を表示」が必要です。',
    'text_gi_developer': '開発元',
    'text_gi_publisher': '発売元',
    'text_gi_year': '発売',
    'text_gi_players': '人数',
    'text_gi_genre': '分類',
    'text_gi_chip': 'チップ',
    'text_gi_footer': 'A: プレイ   B: 戻る   Y: 解説   Sel: チート',
    'text_gi_footer_nav': 'A:プレイ B:戻る Y:解説 Sel:チート {241}{242}:切替',
    'text_gi_footer_full': 'B: 戻る   上下: スクロール',
    'text_gi_footer_man': 'A:プレイ B:戻る Y:解説 X:ガイド Sel:チート',
    'text_gi_footer_nav_man': 'A:プレイ B:戻る Y:解説 X:ガイド Sel:チート {241}{242}:切替',
    'text_gi_footer_pick': 'A: 開く   B: 戻る',
    'text_gi_slug_manual': '説明書',
    'text_gi_slug_guide': '攻略',
    'text_gi_slug_map': 'マップ',
    'text_gi_slug_insert': '付録',
    'text_gi_slug_other': 'その他',
}
