"""Dutch (Nederlands) strings for the sd2snes menu.

Maps const.a65 string labels -> Dutch text. Dutch needs no glyph beyond the shared
accent table (ë, é, ó ... are written as real UTF-8 and encoded by build_const.py).
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
mdesc_* item descriptions ARE rendered (the selected option's help box) and
localized like the rest.
"""

TRANSLATIONS = {
    'text_clkset': 'Tijd instellen A.U.B.',
    'text_mainmenu': 'Hoofdmenu',
    'text_mm_file': 'Verkenner',
    'text_mm_last': 'Spel geschiedenis',
    'text_mm_favorites': 'Favorieten',
    # In-game TAB menu HELP tab.
    'text_igm_hdr_controls': 'IN SPEL SNELTOETSEN',
    'text_igm_open': 'Dit Menu openen',
    'text_igm_save': 'Savestate opslaan',
    'text_igm_load': 'Savestate laden',
    'text_igm_slot': 'Slot kiezen',
    'text_igm_reset_game': 'Spel herstarten',
    'text_igm_reset': 'Herstart naar menu',
    'text_igm_cheats_on': 'Cheats aan',
    'text_igm_cheats_off': 'Cheats uit',
    'text_igm_hooks_off': 'In-spel hooks uit',
    'text_igm_hooks_10s': 'In-spel hooks uit (10 s)',
    'text_igm_pergame': '* Combinatie voor dit spel (savestate_inputs.yml)',
    'text_igm_hdr_keys': 'MENU TOETSEN',
    'text_igm_keys1': 'Links/Rechts: tab   L/R: Eerste/Laatste   A: open',
    'text_igm_keys2': 'B: terug   START: sluiten   SELECT: deze help',
    'text_igm_unavail': 'niet beschikbaar in dit spel',
    'text_igm_key_up': 'Omhoog',
    'text_igm_key_down': 'Omlaag',
    'text_igm_key_left': 'Links',
    'text_igm_key_right': 'Rechts',
    'text_igm_st_title': 'KIES SAVESTATE SLOT',
    'text_igm_st_slot': 'SLOT',
    'text_igm_st_full': 'BEZET',
    'text_igm_st_empty': 'LEEG',
    'text_igm_st_hint_save': 'opslaan',
    'text_igm_st_disabled': 'Savestate slots uitgeschakeld',
    'text_igm_st_hint_load': 'laden',
    'text_igm_st_unavail': 'Savestates niet beschikbaar voor dit spel',
    # In-game TAB menu tab-bar labels (<=10 cols, guarded)
    'text_igm_tab_cheats': 'CHEATS',
    'text_igm_tab_states': 'SAVESTATES',
    'text_igm_tab_saves': 'SAVES',
    'text_igm_tab_help': 'HELP',
    'text_igm_tab_manual': 'GIDS',
    'text_igm_tab_trainer': 'TRAINER',
    # In-game TAB menu SAVES tab (Phase 4, status-only). Field labels <=14 cols, guarded.
    # No umlauts/ss (follow the de convention: ae/oe/ue/ss).
    'text_igm_sv_title': 'Spel opslaan',
    'text_igm_sv_nosram': 'Dit spel heeft geen batterij-opslag',
    'text_igm_sv_file': '.srm bestand:',
    'text_igm_sv_exists': 'BESTAAT',
    'text_igm_sv_missing': 'MIST',
    'text_igm_sv_size': 'Grootte:',
    'text_igm_sv_write': 'Aangepast:',
    'text_igm_sv_autosave': 'Auto-opslaan:',
    'text_igm_sv_on': 'AAN',
    'text_igm_sv_off': 'UIT',
    'text_igm_sv_hint_on': 'Spel wordt automatisch opgeslagen',
    'text_igm_sv_hint_off': 'Automatisch opslaan uit - Opslaan vanuit het spel menu',
    'text_igm_sv_slottitle': 'KIES SRAM-SLOT',
    'text_igm_sv_slot': 'SLOT',
    'text_igm_sv_slothint': 'Bij volgende herstart toegepast',
    'text_igm_mn_title': 'SPEL HANDBOEK',
    'text_igm_mn_read': 'A: Handboek lezen',
    'text_igm_mn_pages': 'paginas',
    'text_igm_mn_notfound': 'Handboek niet gevonden',
    'text_igm_mn_error': 'Fout bij laden handboek',
    'text_igm_mn_guide': 'Handboek',
    'text_igm_mn_select': 'Gids',
    'text_igm_mn_keys1': 'A: Zoom 2x   L/R: pagina wijzigen',
    'text_igm_mn_keys2': 'D-Pad: bewegen   B: terug',
    'text_igm_mn_slug_manual': 'Handboek',
    'text_igm_mn_slug_guide': 'Gids',
    'text_igm_mn_slug_map': 'Kaart',
    'text_igm_mn_slug_insert': 'Bijlage',
    'text_igm_mn_slug_other': 'Anders',

    # In-game TAB menu TRAINER tab (RAM search)
    'text_igm_tr_title': 'RAM-TRAINER',
    'text_igm_tr_searchtype': 'Zoektype:',
    'text_igm_tr_datatype': 'Gegevenstype:',
    'text_igm_tr_value': 'Waarde:',
    'text_igm_tr_candidates': 'Kandidaten:',
    'text_igm_tr_compare': 'Vergelijk:',
    'text_igm_tr_exact': 'Exacte waarde',
    'text_igm_tr_unknown': 'Onbekend',
    'text_igm_tr_8bit': '8-bit',
    'text_igm_tr_16bit': '16-bit',
    'text_igm_tr_eq': 'Gelijk aan',
    'text_igm_tr_ne': 'Ongelijk',
    'text_igm_tr_changed': 'Veranderd',
    'text_igm_tr_unchanged': 'Onveranderd',
    'text_igm_tr_increased': 'Groter',
    'text_igm_tr_decreased': 'Kleiner',
    'text_igm_tr_gt': 'Groter dan',
    'text_igm_tr_lt': 'Kleiner dan',
    'text_igm_tr_newsearch': 'NIEUWE ZOEKOPDRACHT',
    'text_igm_tr_filter': 'FILTEREN',
    'text_igm_tr_results': 'RESULTAAT',
    'text_igm_tr_reset': 'ZOEKEN HERSTARTEN',
    'text_igm_tr_address': 'ADRES',
    'text_igm_tr_current': 'HUIDIG',
    'text_igm_tr_setvalue': 'WAARDE INSTELLEN',
    'text_igm_tr_freeze': 'VASTZETTEN',
    'text_igm_tr_unfreeze': 'LOS KOPPELEN',
    'text_igm_tr_savecheat': 'CHEAT OPSLAAN',
    'text_igm_tr_frozen': 'VASTGEZET',
    'text_igm_tr_searching': 'ZOEKEN...',
    'text_igm_tr_noresults': 'Geen resultaat',
    'text_igm_tr_toomany': 'Teveel resultaten - filter nogmaals',
    'text_igm_tr_dropped_rst': 'Zoeken gewist - console gereset',
    'text_igm_tr_nofreeze': 'Maximaal 4 waardes vastzetten',
    'text_igm_tr_hint_setup': 'A: selecteer   D-Pad: verander',
    'text_igm_tr_hint_edit': 'D-Pad: aanpassen   A: OK   B: terug',
    'text_igm_tr_hint_list': 'A: inspecteer   B: terug',
    'text_igm_tr_master_off': 'Cheat-Master staat uit',
    'text_igm_tr_saved': 'Cheat opgeslagen',
    'text_igm_tr_savefail': 'Cheat niet opgeslagen',
    'text_igm_tr_unpin': 'VAN LIJST VERWIJDEREN',
    'mtext_mm_cfg': 'Configuratie',
    'mtext_mm_sysinfo': 'Systeeminfo',
    'mtext_cfg_time': 'Tijd instellen',
    'mtext_cfg_ask_clock': 'Vragen om de tijd bij het opstarten',
    'mtext_cfg_boot_intro': 'Scherm bij inschakelen',
    'mtext_cfg_warn_exp': 'Waarschuwing experimentele core',
    'mtext_cfg_bsx': 'BS-X Instellingen',
    'mtext_cfg_browser': 'Verkenner-Instellingen',
    'mtext_cfg_chip': 'Chip-Instellingen',
    'mtext_cfg_sgb': 'SGB Instellingen',
    'mtext_cfg_ingame': 'In-spel Instellingen',
    'mtext_cfg_savestates': 'Savestate-Instellingen',
    'mtext_cfg_scic': 'SuperCIC Instellingen',
    'mtext_cfg_patch': 'Patch-Instellingen',
    'mtext_cfg_tour': 'Rondleiding nieuwe functies',
    'mtext_bsx_timesource': 'BS-X tijd',
    'mtext_bsx_time': 'Aangepaste tijd',
    'mtext_scic_enable': 'SuperCIC inschakelen',
    'mtext_scic_vmode_menu': ' {129}Menu videomodus',
    'mtext_scic_vmode_game': ' {129}Spel-videomodus',
    'mtext_scic_buscompat': 'Compatibiliteit bustiming',
    'mtext_browser_sort': 'Mappen sorteren',
    'mtext_browser_hide_ext': 'Verberg extensies',
    'mtext_browser_msu_folders': 'Open MSU-1-mappen als spellen',
    'mtext_browser_sd2snes_dir': 'sd2snes map weergeven',
    'mtext_browser_screensaver': 'Schermbeveiliging',
    'mtext_browser_screensaver_timeout': 'Scherm vervagen na',
    'mtext_browser_ledbright': 'LED helderheid',
    'mtext_ingame_cheats': 'Begin met cheats ingeschakeld',
    'mtext_ingame_shortreset': 'Reset naar menu',
    'mtext_ingame_enable': 'In-spel hook',
    'mtext_ingame_buttons': ' {129}In-spel knoppen',
    'mtext_ingame_cheat_overlay': ' {129}In-Spel menu',
    'mtext_ingame_holdoff': ' {129}Initiële wachttijd',
    'mtext_ingame_savestate': 'In-spel Savestates',
    'mtext_savestate_slots': ' {129}Savestate slots',
    'mtext_loadstate_delay': ' {129}Laadvertraging (beelden)',
    'mtext_sgb_enable_hooks': 'In-spel Hooks',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'SGB functies',
    'mtext_sgb_spr_increase': 'Sprite-limiet (40)',
    'mtext_sgb_volume_boost': 'Volume-Boost',
    'mtext_sgb_clock': 'Frequentie (Kloksnelheid)',
    'mtext_sgb_bios': 'BIOS versie',
    'mtext_ingame_regionpatch': 'Automatisch region patch',
    'mtext_ingame_1chiptransientfixes': '1CHIP Oplossingen',
    'mtext_ingame_brightlimit': 'Helderheidslimiet',
    'mtext_ingame_resetpatch': 'Reset-patch voor klokfase',
    'mtext_ingame_autosave': 'Automatisch opslaan',
    'mtext_ingame_autosave_msu1': ' {129}MSU-1 Automatisch opslaan.',
    'mtext_chip_cx4_speed': 'Cx4 snelheid',
    'mtext_chip_cc_time_limit': "Competition-Cart-Timer (min)",
    'mtext_chip_gsu_speed': 'SuperFX snelheid',
    'mtext_chip_msu1_volume_boost': 'MSU-1 volume',
    'mtext_a26_width': 'Atari 2600 Beeldbreedte',
    'mdesc_mm_last': 'Toon maximaal 10 recent gespeelde spellen',
    'mdesc_mm_favorites': 'Toon tot 20 favoriete spellen',
    'mdesc_mm_cfg': 'Configureer de sd2snes',
    'mdesc_mm_sysinfo': 'Informatie over firmwareversie, SD-kaart, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Datum en tijd instellen',
    'mdesc_cfg_ask_clock': 'Vraag bij het opstarten om de tijd zolang de klok nog niet is ingesteld',
    'mdesc_cfg_boot_intro': 'Toont een openingsscherm, met geluid, bij het inschakelen van de console',
    'mdesc_cfg_warn_exp': 'Vraagt voor het starten van een spel op een experimentele console-core (NES, Master System, Atari 2600, Game Boy Color)',
    'mdesc_cfg_bsx': 'Specifieke instellingen voor BS-X/Satellaview',
    'mdesc_cfg_browser': 'Instellingen voor verkenner wijzigen',
    'mdesc_cfg_chip': 'Speciale chipfuncties instellen',
    'mdesc_cfg_ingame': 'In-spel functies instellen',
    'mdesc_cfg_sgb': 'Super Game Boy functies',
    'mdesc_cfg_savestates': 'Savestates functies instellen',
    'mdesc_cfg_scic': 'SuperCIC in-/uitschakelen en videomodus instellen',
    'mdesc_cfg_patch': 'Opties voor IPS/BPS patching',
    'mdesc_cfg_tour': 'Toon de rondleiding van de eerste start opnieuw',
    'mdesc_bsx_timesource': 'Kies de datum en tijd die BS-X spellen zien',
    'mdesc_bsx_time': 'Stel een aangepaste tijd en datum in voor BS-X spellen',
    'mdesc_scic_enable': 'Vereist voor SuperCIC-functies',
    'mdesc_scic_vmode_menu': 'Videomodus voor menu instellen',
    'mdesc_scic_vmode_game': 'Videomodus voor spellen',
    'mdesc_scic_buscompat': 'Beperk de timing van de cartridgebus voor consoles waarbij sommige spellen vastlopen of haperen. Schakel dit alleen in als je console soms vastloopt.',
    'mdesc_browser_sort': 'Kies of bestanden moeten worden gesorteerd',
    'mdesc_browser_hide_ext': 'Kies of bestandsextensies moeten worden verborgen',
    'mdesc_browser_msu_folders': 'A op een map waarvan de enige ROM een MSU-1-spel is, start dat spel',
    'mdesc_browser_sd2snes_dir': 'Toon /sd2snes in de bestandenlijst',
    'mdesc_browser_screensaver': 'Laat het scherm na verloop van tijd langzaam vervagen',
    'mdesc_browser_screensaver_timeout': 'Stel de tijd in waarna het scherm moet vervagen',
    'mdesc_browser_ledbright': 'Helderheid van de LEDs wijzigen',
    'mdesc_ingame_cheats': 'Of cheats bij het starten ingeschakeld zijn (kan met de in-spel knoppen worden gewijzigd)',
    'mdesc_ingame_shortreset': 'Waar een reset heen gaat. Map/ROM openen de laatste spelmap opnieuw. Duur: kort drukken reset het spel, lang drukken gaat naar de ROM.',
    'mdesc_ingame_enable': 'Vereist voor het in-spel menu, savestates, in-spel knoppen en cheats die het geheugen van het spel wijzigen',
    'mdesc_ingame_buttons': 'Schakel knoppen in het spel in (reset, cheats in-/uitschakelen{127}{128}). Vereist dat de in-spel hook is ingeschakeld.',
    'mdesc_ingame_cheat_overlay': 'In-spel menu (houd L+R+Y+Links): cheats, savestates, saves en gidsen. Vereist de in-spel hook. Niet voor enkele spellen met speciale chips.',
    'mdesc_ingame_holdoff': 'Wacht 10 seconden voordat je de hook inschakelt (dit helpt sommige spellen op te starten met de hook ingeschakeld)',
    'mdesc_ingame_savestate': 'Schakel in-spel savestates in en kies een controller. Standaard: Opslaan - Start+R / Laden - Start+L',
    'mdesc_savestate_slots': 'Schakel savestate-slots in. Select + D-pad: elke richting komt overeen met een slot dat je kunt kiezen',
    'mdesc_loadstate_delay': 'Pas de vertraging voor het laden van savestates aan (beelden)',
    'mdesc_sgb_enable_hooks': 'Vereist voor in-spel knoppen',
    'mdesc_sgb_enable_state': 'Schakel ingebouwde savestates in op de SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'SGB-verbeteringen uitschakelen/inschakelen',
    'mdesc_sgb_spr_increase': 'Verhoog het aantal toegestane zichtbare sprites',
    'mdesc_sgb_volume_boost': 'Stel de volumeversterking in voor SGB-audio als het geluid te zacht is',
    'mdesc_sgb_clock': 'Past de SGB-klok (frequentie) aan',
    'mdesc_sgb_bios': 'Selecteer een SGB-firmware-/BIOS-versie',
    'mdesc_ingame_regionpatch': 'Omzeil eenvoudige regiobeveiliging van games',
    'mdesc_ingame_1chiptransientfixes': 'Helderheid instellen om synchronisatiefouten, vervagende scanlijnen en ontbrekende schaduwen op 1CHIP/Jr.-consoles te verhelpen.',
    'mdesc_ingame_brightlimit': 'Beperk de algehele helderheid (bijv. bij 1CHIP-consoles om te voldoen aan RGB-lijnniveaus)',
    'mdesc_ingame_resetpatch': 'Schakel de reset-patch in om de klokken te synchroniseren. Lost grafische problemen in sommige spellen op',
    'mdesc_ingame_autosave': 'SRM bestand automatisch opslaan wanneer de inhoud van het opslaggeheugen (Save RAM) wijzigt',
    'mdesc_ingame_autosave_msu1': 'MSU-1: Het SRM-bestand wordt op bepaalde momenten automatisch opgeslagen. Dit kan leiden tot een korte hapering.',
    'mdesc_chip_cx4_speed': 'Snelheid van Cx4 soft core instellen',
    'mdesc_chip_cc_time_limit': "Rondetijd voor Campus Challenge '92 / PowerFest '94",
    'mdesc_chip_gsu_speed': 'Snelheid van SuperFX soft core instellen',
    'mdesc_chip_msu1_volume_boost': 'Stel de volumeversterking voor MSU1-audio in als je sd2snes te zacht klinkt (Rev. E-G)',
    'mdesc_a26_width': 'Atari 2600-beeldbreedte: 160 is de native 1:1-verhouding, 256 vult het scherm',
    'mdesc_cx4_speed_fast': 'Zo snel mogelijk uitvoeren',
    'mdesc_cx4_speed_normal': 'Op ongeveer de oorspronkelijke snelheid uitvoeren',
    'mdesc_gsu_speed_fast': 'Zo snel mogelijk uitvoeren',
    'mdesc_gsu_speed_normal': 'Op ongeveer de oorspronkelijke snelheid uitvoeren',
    'text_filesel_selected_file': 'Geselecteerd bestand',
    'text_filesel_context_add_to_favorites': 'Toevoegen aan favorieten',
    'mdesc_filesel_context_add_to_favorites': 'Voeg het geselecteerde bestand toe aan de favorieten',
    'text_filesel_context_remove_from_favorites': 'Uit favorieten verwijderen',
    'mdesc_filesel_context_remove_from_favorites': 'Verwijder het geselecteerde bestand uit de favorieten',
    'text_recent_context_remove_from_recent': 'Uit spel geschiedenis verwijderen',
    'mdesc_recent_context_remove_from_recent': 'Verwijder het geselecteerde bestand uit de spel geschiedenis lijst',
    'text_filesel_set_as_autoboot': 'Als automatisch opstarten instellen',
    'mdesc_filesel_set_as_autoboot': 'Start deze ROM automatisch bij de volgende keer inschakelen (houd START ingedrukt tijdens het inschakelen/resetten om te annuleren)',
    'text_filesel_set_as_bgm': 'Als menumuziek instellen',
    'mdesc_filesel_set_as_bgm': 'Gebruik dit SPC-bestand als achtergrondmuziek voor het menu',
    'text_filesel_context_delete_file': 'Verwijderen',
    'mdesc_filesel_context_delete_file': 'Het geselecteerde bestand verwijderen',
    'text_filesel_context_delete_srm': 'Opslagbestand verwijderen',
    'mdesc_filesel_context_delete_srm': 'Verwijder het SRM-opslagbestand voor deze ROM',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': 'Bekijk en schakel cheats in of uit vanuit het YAML-bestand van deze ROM',
    'text_filesel_context_gameinfo': 'Spelinformatie',
    'mdesc_filesel_context_gameinfo': 'Toon het informatiescherm van deze ROM (hoes, screenshot en metadata) voordat het spel wordt gestart',
    'text_cheat_yes': 'Ja ',
    'text_cheat_no': 'Nee',
    'text_cheat_none_title': 'Cheats',
    'text_ce_name': 'Naam',
    'text_cheat_none_msg': 'Geen cheats gevonden voor deze ROM',
    'text_confirm_delete_file': 'Dit bestand verwijderen?',
    'text_confirm_delete_srm': 'Verwijder het opslagbestand?',
    'text_confirm_hint': 'A:Bevestig.  B:annuleer',
    'text_confirm_no_sel': '[Nee]',
    'text_confirm_no_unsel': 'Nee ',
    'text_confirm_yes_sel': '[Ja]',
    'text_confirm_yes_unsel': ' Ja ',
    'text_statusbar_play': 'A:Speel B:Terug X:Menu',
    'text_statusbar_keys': 'A:Kies B:Terug X:Menu Y:context',
    'text_statusbar_spc': 'B:Terug',
    'text_statusbar_menu': 'A:Kies B:Terug',
    'text_last': 'Spel geschiedenis',
    'text_favorite': 'Favoriete spellen',
    'text_no_last': 'Geen spel geschiedenis',
    'text_no_favorite': 'Geen Favoriete spellen',
    'text_favorites_full': 'Favorietenlijst is vol',
    'text_err_supplfile': 'Vereist bestand ontbreekt:',
    'text_err_noimpl': 'Chip niet ondersteund:',
    'text_err_nohw': 'Vereist Mk.III hardware:',
    'text_err_generic': 'Laadfout:',
    'text_exp_title': '*Experimentele* core',
    'text_exp_l1': 'Deze is nog in ontwikkeling:',
    'text_exp_l2': '- kan traag zijn, met geluids- en',
    'text_exp_l3': '  grafische fouten',
    'text_exp_l4': '- sommige spellen werken mogelijk niet',
    'text_exp_l5': '- savestates en het in-game menu zijn',
    'text_exp_l6': '  nog niet beschikbaar',
    'text_exp_start': 'Starten',
    'text_exp_back': 'Terug',
    'text_exp_nowarn': 'Starten, niet meer melden',
    'text_on_p1': 'Aan: P1',
    'text_on_p2': 'Aan: P2',
    'text_on': 'Aan',
    'text_off': 'Uit',
    'text_15_max': '15 (max)',
    'text_theme': 'Thema',
    'text_cover_large': 'Groot',
    'text_cover_small': 'Klein',
    'text_gameinfo_context': 'Context',
    'text_nav_folder': 'Map',
    'text_nav_rom': 'ROM',
    'text_nav_duration': 'Duur',
    'text_enabled': 'Ingeschakeld',
    'text_disabled': 'Uitgeschakeld',
    'text_normal': 'Normaal',
    'text_fast': 'Snel',
    'text_a26_w256': '256 (breed)',
    'text_rtc': 'Werkelijke tijd',
    'text_custom': 'aangepast',
    'text_yes': 'Ja',
    'text_no': 'Nee',
    'text_onbg_question': 'Een rondleiding door het nieuws?',
    'text_onbg_lang': 'Taal:',
    'text_onbg_hint': '(A) Ja        (B) Nee',
    'text_auto': 'Automatisch',
    'text_add': 'Toevoegen',
    'text_remove': 'Verwijderen',
    'text_edit': 'Bewerken',
    'text_save': 'Opslaan',
    'text_1min': '1 min',
    'text_2min': '2 min',
    'text_3min': '3 min',
    'text_4min': '4 min',
    'text_5min': '5 min',
    'text_10min': '10 min',
    'text_15min': '15 min',
    'text_20min': '20 min',
    'text_30min': '30 min',
    'text_45min': '45 min',
    'text_60min': '1 uur',
    'text_spcplay': 'SPC-speler',
    'text_spcload': 'SPC-gegevens in SPC700 inladen{127}{128}',
    'text_spcstarta': '**** Speelt nu SPC nummer ****',
    'text_spcstartb': 'Naam:  ',
    'text_spcstartc': 'Lied:  ',
    'text_spcstartd': 'Artiest:',
    'text_spc_statusbar': 'B:Terug',
    'text_loading': 'Laden{127}{128}                            ',
    'text_saving': 'Opslaan{127}{128}                      ',
    'text_cheat': 'Cheats voor ',
    'text_cheat_noname': '(geen naam)',
    'text_igm_cheat_noname': '(geen naam)',
    'text_igm_ch_none': 'Geen cheats',
    'text_igm_ft_tab': '<>:TAB L/R:EINDEN A:OPENEN SEL:HELP B:SLUITEN',
    'text_igm_ft_cheats': 'A:AAN/UIT Y:BEWERKEN SEL:TOEVOEGEN X:CHEATS B:TERUG',
    'text_igm_ft_generic': 'A:SELECTEER B:TERUG',
    'text_igm_master_on': 'CHEATS: AAN',
    'text_igm_master_off': 'CHEATS: UIT',
    'text_igm_ft_ce_edit': 'A:BEWERKEN SEL:CODE TOEVOEGEN Y:VERWIJDEREN B:TERUG',
    'text_igm_ft_ce_kbd': 'A:TYPEN Y:VERWIJDEREN SEL:SPATIE X:OK B:ANNULEREN',
    'text_igm_ft_help': 'B:TERUG START:SLUITEN',
    'text_igm_ce_title_new': 'NIEUWE CHEAT',
    'text_igm_ce_title_edit': 'CHEAT AANPASSEN',
    'text_igm_ce_name': 'Naam:',
    'text_igm_ce_save': 'OPSLAAN',
    'text_igm_ce_delete': 'CHEAT VERWIJDEREN',
    'text_igm_ce_confirm': 'Deze cheat verwijderen?',
    'text_igm_ce_confirm_keys': 'A: ja   B: nee',
    'text_igm_ce_nosup': 'Werk de firmware A.U.B. bij',
    'text_igm_ce_full': 'De lijst met cheats zit vol',
    'text_igm_ce_badcode': 'Ongeldige code',
    # System Information screen. {N} = a value the menu substitutes (see si_fmt_tbl);
    # {34} is a quote and {127}{128} the ellipsis. Every placeholder of the English
    # base must appear here exactly as often -- build_const.py fails the build otherwise.
    'text_si_fw': '    Firmware versie: {2}',
    'text_si_busy': 'Vrije ruimte berekenen{127}{128}',
    'text_si_removed': '    *** SD verwijderd/USB bezet ***',
    'text_si_maker': 'SD fabrikant/OEM:   0x{3}, {34}{4}{34}',
    'text_si_product': 'SD productnaam: {34}{5}{34}, Rev. {6}.{7}',
    'text_si_serial': 'SD serienr.:   {8}, Fabr. {9}/{10}',
    'text_si_acc': 'SD-toegangstijd:  {11}.{12} / {13}.{14} ms avg/max',
    'text_si_accmeas': 'SD-toegangstijd:  meting{127}{128}',
    'text_si_usage': 'SD verbruik: {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': 'controleren{127}{128}',
    'text_si_sgb_missing': 'Mist',
    'text_si_sgb_mismatch': 'Afwijkend ',
    'text_si_sgb_ok': 'ok',
    'text_si_cic': 'CIC Status: {19}',
    'text_si_clk': 'SNES frequentie: {20}Hz',
    'text_si_clkmeas': 'SNES frequentie: meting{127}{128}',
    'text_si_u16on': 'Ultra16 serienr. {21} (Autoboot Aan)',
    'text_si_u16off': 'Ultra16 serienr. {21} (Autoboot Uit)',
    'text_si_model': 'Model: {22}',
    'text_si_updatefw': '*** Werk de firmware A.U.B. bij ***',
    # --- RAM connection test screen (snes/memtest.a65). text_mtl_* are whole
    #     40-column lines; text_mt_* are fragments printed after an untranslated
    #     "U501: " chip prefix and followed by the LINE NUMBER, so each must end
    #     exactly where that number goes.
    'mtext_mm_memtest': 'Geheugentest',
    'mdesc_mm_memtest': 'Test de bedrading FPGA-RAM en daarna elke cel (30 s). Reset de console.',
    'text_mtl_prompt': 'A: Test starten  B: Sluiten',
    'text_mtl_prompt2': 'Reset de console. Duurt ca. 30s.',
    'text_mtl_run': 'Test het geheugen, wacht A.U.B.{127}{128}',
    'text_mtl_none': 'Er is nog geen test uitgevoerd.',
    'text_mtl_pass': 'Alle RAM-lijnen OK.',
    'text_mtl_fail': 'Fout gevonden:',
    'text_mtl_nocore': '/sd2snes/fpga_test mist of is defect.',
    'text_mtl_more': '(meer fouten niet weergegeven)',
    'text_mtl_cellpass': 'Alle cellen zijn geverifieerd.',
    'text_mtl_cellfail': 'Eerste defecte cel bij 0x',
    'text_mtl_cellskip': 'Celtest overgeslagen: herstel bedrading.',
    'text_mt_data': 'controleer datalijn D',
    'text_mt_addr': 'controleer adreslijn A',
    'text_mt_short': 'mogelijk kortsluiting A',
    'text_mt_bytesel': 'controleer LB# / UB#',
    'text_mt_ctrl': 'controleer CE# / OE# / WE#',
    'text_mt_fpgactrl': 'controleer FPGA CE# / OE# / WE#',

    # --- PCM player screen (snes/pcmplay.a65) ---
    'text_pcm_title': 'PCM-speler',
    'text_pcm_prompt': 'A: Speel/Pauzeer   B: Sluit',
    'text_pcm_promptb': 'B: Sluit',
    'text_pcm_paused': 'Pauzeer',
    'text_pcm_erropen': 'Bestand kan niet gelezen worden.',
    'text_pcm_errmagic': 'Geen MSU-1-PCM bestand.',
    'text_pcm_nosup': '*** Werk de firmware A.U.B. bij ***',
    'text_st_slotb_title': 'Sufami Turbo - Slot B',
    'text_st_slotb_footer': 'A:Start  B:Terug  <>:Pagina  LR:Einde',
    'text_st_slotb_none': '[Geen Slot B cartridge]',
    'text_ips_nopatch': '[Geen Patch]',
    'text_ips_header': 'Patches',
    'mtext_patch_verify': 'Integriteit verifiëren (~23s)',
    'mtext_patch_clearppu': 'Leeg PPU bij starten',
    'mdesc_patch_verify': 'Gepatchte ROM opnieuw lezen om te verifiëren (veel trager)',
    'mdesc_patch_clearppu': 'VRAM/CGRAM/OAM legen alvorens gepatchten ROM start (romhacks zonder PPU-Init)',
    'text_patch_hdr_auto': 'Automatisch  ',
    'text_patch_hdr_on': 'Header',
    'text_patch_hdr_off': 'Ruw    ',
    'text_patch_footer': 'A:Start  Y:Meer  B:Terug  <>:Pagina  LR:Einde',
    'text_patch_creating': 'Gepatchte ROM maken...',
    'text_err_patchexport': 'Gepatchte ROM: schrijffout',
    'text_patch_export_ok': 'Gepatchte ROM aangemaakt',
    'text_patch_export_part': 'ROM ok, Assets onvolledig',
    'text_patch_export_exists': 'Gepatchte ROM bestaat reeds',
    'text_patch_hdrsel_auto': 'Automatisch (herkennen)',
    'text_patch_hdrsel_on': 'Met header',
    'text_patch_hdrsel_off': 'Zonder header',
    'mtext_patch_header_mode': 'Header modus',
    'mdesc_patch_header_mode': 'Hoe de IPS-offsets worden gelezen: Automatisch, Header (verschuiving van 512 bytes) of Ruw.',
    'mtext_patch_create_rom': 'Gepatchte ROM maken',
    'mdesc_patch_create_rom': 'Schrijf de gepatchte ROM naast het origineel, genoemd naar de patch, met hoes, saves, cheats en gidsen erbij gekopieerd. Duurt minuten.',
    'cheat_tab_head': 'Naam                                     Actief',
    'cheat_tab_hint_text': ' A:Aan/Uit Y:Bewerk Sel:Nieuw B:afsluiten',
    'mtext_browser_showcov': 'Hoesjes weergeven',
    'mdesc_browser_showcov': 'Spelhoesjes in Menu weergeven',
    'mtext_browser_covlists': ' {129}Favorieten/Geschiedenis',
    'mdesc_browser_covlists': 'Hoesjes ook in Geschiedenis en Favorieten weergeven',
    'mtext_browser_menumusic': 'Menu muziek',
    'mtext_browser_menumusic_random': ' {129}Willekeurige muziek',
    'mtext_browser_menusfx': 'Menu geluiden',
    'mtext_browser_text_outline': 'Tekst contour',
    'mtext_browser_text_aa': 'Tekst anti-aliasing',
    'mdesc_browser_menumusic': 'Speel achtergrond muziek (menu.spc) in het menu',
    'mtext_browser_sortfav': 'Favorieten sorteren',
    'mdesc_browser_sortfav': 'Favorietenlijst alfabetisch sorteren',
    'mtext_browser_restoretheme': 'Thema herstellen',
    'mdesc_browser_restoretheme': 'Menu thema naar standaard terug zetten',
    'mtext_browser_restoreclassic': 'Naar klassiek thema herstellen',
    'mdesc_browser_restoreclassic': 'klassieke sd2snes uiterlijk starten (/sd2snes/classic.thm moet aanwezig zijn)',
    'mtext_browser_restoremusic': 'Muziek herstellen',
    'mdesc_browser_restoremusic': 'Standaard menu muziek terugzetten (menu.spc)',
    'mdesc_browser_menumusic_random': 'Willekeurige muziek (.spc) spelen uit de /sd2snes/music map',
    'mdesc_browser_text_outline': 'Donkere contour om de menutekst: volgt het thema of het afdwingen',
    'mdesc_browser_text_aa': 'Gladde randen bij de menutekst: het thema volgen of het afdwingen',
    'text_mm_language': 'Taal',
    'mdesc_mm_language': 'Stel de taal voor het menu/de firmware in',
    'mdesc_browser_menusfx': 'Speel geluidseffecten af bij het navigeren door het menu',
    'mtext_browser_gameinfo': 'Spel informatie',
    'mtext_gameinfo_enable': 'Informatiescherm weergeven',
    'mdesc_browser_gameinfo': 'Toon hoesje, schermafbeelding en informatie voordat een ROM wordt opgestart die een /sd2snes/info-vermelding heeft',
    'mdesc_cfg_gameinfo': 'Opties voor het spelinformatiescherm vóór het opstarten',
    'mtext_browser_gameinfo_video': ' {129}Video tonen',
    'mdesc_browser_gameinfo_video': 'Speel de geanimeerde clip af op het spelinformatiescherm (bij uit wordt een statische afbeelding getoond).',
    'mtext_browser_gameinfo_music': ' {129}Video muziek',
    'mdesc_browser_gameinfo_music': 'Speel de geluidspoor van de clip af terwijl deze wordt weergegeven. Vereist video weergeven.',
    'text_gi_developer': 'Ontwikkelaar',
    'text_gi_publisher': 'Uitgever',
    'text_gi_year': 'Jaar',
    'text_gi_players': 'Speler',
    'text_gi_genre': 'Genre',
    'text_gi_chip': 'Chip',
    'text_gi_footer': 'A: Speel  B: Terug  Y: Omschrijving  Sel: Cheats',
    'text_gi_footer_nav': 'A:Speel B:Terug Y:Omschr. Sel:Cheats {241}{242}:Spel',
    'text_gi_footer_full': 'B: Terug  Omhoog/Omlaag: Scrollen',
    'text_gi_footer_man': 'A:Speel B:Terug Y:Omschr. X:Gids Sel:Cheats',
    'text_gi_footer_nav_man': 'A:Speel B:Terug Y:Omschr. X:Gids Sel:Cheats {241}{242}:Spel',
    'text_gi_footer_pick': 'A: Open  B: Terug',
    'text_gi_slug_manual': 'Handboek',
    'text_gi_slug_guide': 'Gids',
    'text_gi_slug_map': 'Kaart',
    'text_gi_slug_insert': 'Bijlage',
    'text_gi_slug_other': 'Anders',

    # Game Boy Color core, controller-2 hooks and the per-row cheat ON/OFF token.
    'mtext_ingame_pad2': ' {129}Knoppen op controller 2',
    'mdesc_ingame_pad2': 'Accepteer de in-spel knopcombinaties ook van de controller in poort 2. Kost bij elke interrupt wat extra tijd.',
    'mtext_gbc_mode': 'Game Boy Color modus',
    'mtext_gbc_sync': 'Game Boy Color sync',
    'mtext_gbc_stretch': 'Game Boy Color uitrekken',
    'mdesc_gbc_mode': 'Core voor Game Boy-spellen: SGB of GBC. Alleen Mk.III',
    'mdesc_gbc_sync': 'Genlock: vloeiend. Exact: echte snelheid, kan beelden overslaan. Alleen Mk.III',
    'mdesc_gbc_stretch': 'Hi-colour-schermen vullen 256x192. Alleen Mk.III',
    'text_gbc_prefer_sgb': 'Voorkeur SGB',
    'text_gbc_prefer_gbc': 'Voorkeur GBC',
    'text_gbc_genlock': 'Genlock',
    'text_gbc_exact': 'Exact',
    'text_cheat_flag_on': 'AAN',
    'text_cheat_flag_off': 'UIT',
    'text_igm_cheat_on': 'AAN',
    'text_igm_cheat_off': 'UIT',
}
