"""Simplified Chinese strings for the sd2snes menu (简体中文).

CJK characters are drawn from the glyph cache in VRAM (snes/cjk.a65): build_const.py moves
this whole column, with its glyphs, into lang_zh.bin, which the menu loads into WRAM
when the language is selected. Any label left out falls back to English.
"""

TRANSLATIONS = {
    'text_clkset': '请设置时间',
    'text_mainmenu': '主菜单',
    'text_mm_file': '文件浏览器',
    'text_mm_last': '最近游戏',
    'text_mm_favorites': '收藏游戏',
    'text_igm_hdr_controls': '游戏内快捷键',
    'text_igm_open': '打开本菜单',
    'text_igm_save': '即时存档',
    'text_igm_load': '即时读档',
    'text_igm_slot': '选择栏位',
    'text_igm_reset_game': '重置游戏',
    'text_igm_reset': '返回菜单',
    'text_igm_cheats_on': '开启金手指',
    'text_igm_cheats_off': '关闭金手指',
    'text_igm_hooks_off': '停用钩子',
    'text_igm_hooks_10s': '停用钩子 10 秒',
    'text_igm_pergame': '* 本游戏使用专属组合键 (savestate_inputs.yml)',
    'text_igm_hdr_keys': '菜单按键',
    'text_igm_keys1': '左右:切换标签  L/R:跳到首尾  A:打开',
    'text_igm_keys2': 'B:返回  START:关闭  SELECT:显示本帮助',
    'text_igm_unavail': '本游戏不可用',
    'text_igm_key_up': '上',
    'text_igm_key_down': '下',
    'text_igm_key_left': '左',
    'text_igm_key_right': '右',
    'text_igm_st_title': '选择即时存档栏位',
    'text_igm_st_slot': '栏位',
    'text_igm_st_full': '已占用',
    'text_igm_st_empty': '空',
    'text_igm_st_hint_save': '存档',
    'text_igm_st_disabled': '即时存档栏位已停用',
    'text_igm_st_hint_load': '读档',
    'text_igm_st_unavail': '本游戏不支持即时存档',
    'text_igm_tab_cheats': '金手指',
    'text_igm_tab_states': '即时存档',
    'text_igm_tab_saves': '存档',
    'text_igm_tab_help': '帮助',
    'text_igm_tab_manual': '攻略',
    'text_igm_tab_trainer': '修改器',
    'text_igm_sv_title': '游戏存档',
    'text_igm_sv_nosram': '本游戏没有电池存档',
    'text_igm_sv_file': '.srm文件:',
    'text_igm_sv_exists': '已存在',
    'text_igm_sv_missing': '不存在',
    'text_igm_sv_size': '大小:',
    'text_igm_sv_write': '最后写入:',
    'text_igm_sv_autosave': '自动保存:',
    'text_igm_sv_on': '开',
    'text_igm_sv_off': '关',
    'text_igm_sv_hint_on': '游戏过程中存档会自动写入',
    'text_igm_sv_hint_off': '自动保存已关闭 - 请用游戏自身的存档功能',
    'text_igm_sv_slottitle': '选择SRAM栏位',
    'text_igm_sv_slot': '栏位',
    'text_igm_sv_slothint': '下次启动游戏时生效',
    'text_igm_mn_title': '游戏说明书',
    'text_igm_mn_read': 'A:阅读说明书',
    'text_igm_mn_pages': '页',
    'text_igm_mn_notfound': '未找到说明书',
    'text_igm_mn_error': '说明书载入失败',
    'text_igm_mn_guide': '攻略',
    'text_igm_mn_select': '选择攻略',
    'text_igm_mn_keys1': 'A:放大2倍  L/R:翻页',
    'text_igm_mn_keys2': '方向键:移动  B:返回',
    'text_igm_mn_slug_manual': '说明书',
    'text_igm_mn_slug_guide': '攻略',
    'text_igm_mn_slug_map': '地图',
    'text_igm_mn_slug_insert': '插页',
    'text_igm_mn_slug_other': '其他',
    'text_igm_tr_title': 'RAM修改器',
    'text_igm_tr_searchtype': '搜索方式:',
    'text_igm_tr_datatype': '数据类型:',
    'text_igm_tr_value': '数值:',
    'text_igm_tr_candidates': '候选地址:',
    'text_igm_tr_compare': '比较:',
    'text_igm_tr_exact': '精确数值',
    'text_igm_tr_unknown': '未知数值',
    'text_igm_tr_8bit': '8位',
    'text_igm_tr_16bit': '16位',
    'text_igm_tr_eq': '等于',
    'text_igm_tr_ne': '不等于',
    'text_igm_tr_changed': '有变化',
    'text_igm_tr_unchanged': '无变化',
    'text_igm_tr_increased': '增加了',
    'text_igm_tr_decreased': '减少了',
    'text_igm_tr_gt': '大于',
    'text_igm_tr_lt': '小于',
    'text_igm_tr_newsearch': '开始新搜索',
    'text_igm_tr_filter': '筛选',
    'text_igm_tr_results': '查看结果',
    'text_igm_tr_reset': '重置搜索',
    'text_igm_tr_address': '地址',
    'text_igm_tr_current': '当前值',
    'text_igm_tr_setvalue': '修改数值',
    'text_igm_tr_freeze': '锁定数值',
    'text_igm_tr_unfreeze': '解除锁定',
    'text_igm_tr_savecheat': '存为金手指',
    'text_igm_tr_frozen': '已锁定',
    'text_igm_tr_searching': '搜索中...',
    'text_igm_tr_noresults': '已无符合条件的结果',
    'text_igm_tr_toomany': '结果过多 - 请继续筛选',
    'text_igm_tr_dropped_rst': '主机已重置，搜索已清空',
    'text_igm_tr_nofreeze': '最多只能锁定4个数值',
    'text_igm_tr_hint_setup': 'A:选择  方向键:更改',
    'text_igm_tr_hint_edit': '方向键:编辑  A:确定  B:取消',
    'text_igm_tr_hint_list': 'A:查看  B:返回',
    'text_igm_tr_master_off': '金手指总开关已关闭',
    'text_igm_tr_saved': '金手指已保存',
    'text_igm_tr_savefail': '无法保存金手指',
    'text_igm_tr_unpin': '从列表移除',
    'mtext_mm_cfg': '设置',
    'mtext_mm_sysinfo': '系统信息',
    'mtext_cfg_time': '设置时钟',
    'mtext_cfg_ask_clock': '开机时询问时间',
    'mtext_cfg_boot_intro': '开机画面',
    'mtext_cfg_warn_exp': '实验性核心提示',
    'mtext_cfg_bsx': 'BS-X设置',
    'mtext_cfg_browser': '文件浏览器设置',
    'mtext_cfg_chip': '特殊芯片选项',
    'mtext_cfg_sgb': 'SGB设置',
    'mtext_cfg_ingame': '游戏内设置',
    'mtext_cfg_savestates': '即时存档设置',
    'mtext_cfg_scic': 'SuperCIC设置',
    'mtext_cfg_tour': '新功能导览',
    'mtext_bsx_timesource': 'BS-X时钟',
    'mtext_bsx_time': '自定义时间',
    'mtext_scic_enable': '启用SuperCIC',
    'mtext_scic_vmode_menu': ' {129}菜单视频制式',
    'mtext_scic_vmode_game': ' {129}游戏视频制式',
    'mtext_scic_buscompat': '总线时序兼容',
    'mtext_browser_sort': '文件列表排序',
    'mtext_browser_hide_ext': '隐藏扩展名',
    'mtext_browser_msu_folders': '将MSU-1文件夹视为游戏',
    'mtext_browser_sd2snes_dir': '显示sd2snes文件夹',
    'mtext_browser_screensaver': '屏幕保护',
    'mtext_browser_screensaver_timeout': '变暗等待时间',
    'mtext_browser_ledbright': 'LED亮度',
    'mtext_ingame_cheats': '启动时开启金手指',
    'mtext_ingame_shortreset': '重置键返回菜单',
    'mtext_ingame_enable': '游戏内钩子',
    'mtext_ingame_pad2': ' {129}2P手柄快捷键',
    'mtext_ingame_buttons': ' {129}游戏内快捷键',
    'mtext_ingame_cheat_overlay': ' {129}游戏内菜单',
    'mtext_ingame_holdoff': ' {129}启动延迟',
    'mtext_ingame_savestate': '游戏内即时存档',
    'mtext_savestate_slots': ' {129}即时存档栏位',
    'mtext_loadstate_delay': ' {129}读档延迟(帧)',
    'mtext_sgb_enable_hooks': '游戏内钩子',
    'mtext_sgb_enable_state': '即时存档(XR, XL)',
    'mtext_sgb_enh_override': 'SGB增强功能',
    'mtext_sgb_spr_increase': '精灵数上限(40)',
    'mtext_sgb_volume_boost': '音量增强',
    'mtext_sgb_clock': '时钟(时序)',
    'mtext_sgb_bios': 'BIOS版本',
    'mtext_gbc_mode': 'Game Boy Color模式',
    'mtext_gbc_sync': 'Game Boy Color同步',
    'mtext_gbc_stretch': 'Game Boy Color拉伸',
    'mtext_ingame_regionpatch': '自动区域补丁',
    'mtext_ingame_1chiptransientfixes': '1CHIP瞬态修正',
    'mtext_ingame_brightlimit': '亮度上限',
    'mtext_ingame_resetpatch': '时钟相位重置补丁',
    'mtext_ingame_autosave': '自动保存',
    'mtext_ingame_autosave_msu1': ' {129}MSU-1自动保存',
    'mtext_chip_cx4_speed': 'Cx4速度',
    'mtext_chip_cc_time_limit': '比赛卡带计时(分钟)',
    'mtext_chip_gsu_speed': 'SuperFX速度',
    'mtext_chip_msu1_volume_boost': 'MSU-1音量增强',
    'mtext_a26_width': 'Atari 2600画面宽度',
    'mdesc_mm_last': '显示最近玩过的10款游戏',
    'mdesc_mm_favorites': '显示最多20款收藏游戏',
    'mdesc_mm_cfg': '设置sd2snes',
    'mdesc_mm_sysinfo': '查看固件版本、SD卡、SNES、CIC{127}{128}',
    'mdesc_cfg_time': '设置日期和时间',
    'mdesc_cfg_ask_clock': '时钟未设置时，开机询问时间',
    'mdesc_cfg_boot_intro': '主机开机时显示带提示音的开场画面',
    'mdesc_cfg_warn_exp': '在实验性主机核心（NES、Master System、Atari 2600、Game Boy Color）上启动游戏前先询问',
    'mdesc_cfg_bsx': 'BS-X/Satellaview专用设置',
    'mdesc_cfg_browser': '更改文件浏览器设置',
    'mdesc_cfg_chip': '设置特殊芯片功能',
    'mdesc_cfg_ingame': '设置游戏内功能',
    'mdesc_cfg_sgb': '设置Super Game Boy功能',
    'mdesc_cfg_savestates': '设置即时存档功能',
    'mdesc_cfg_scic': '启用/停用SuperCIC并设置视频制式',
    'mdesc_cfg_tour': '再次显示首次开机时的新功能导览',
    'mdesc_bsx_timesource': '选择BS-X游戏使用的日期和时间',
    'mdesc_bsx_time': '为BS-X游戏设置自定义日期和时间',
    'mdesc_scic_enable': '使用SuperCIC增强功能时必须开启',
    'mdesc_scic_vmode_menu': '设置菜单的视频制式',
    'mdesc_scic_vmode_game': '设置游戏的视频制式',
    'mdesc_scic_buscompat': '缩短卡带总线时序，适用于部分游戏会死机或花屏的主机。仅在本主机出现死机时开启。',
    'mdesc_browser_sort': '选择是否对文件列表排序',
    'mdesc_browser_hide_ext': '选择是否隐藏文件扩展名',
    'mdesc_browser_msu_folders': '文件夹内只有一个MSU-1 ROM时，按A直接启动该游戏',
    'mdesc_browser_sd2snes_dir': '在文件列表中显示/sd2snes',
    'mdesc_browser_screensaver': '一段时间无操作后屏幕逐渐变暗',
    'mdesc_browser_screensaver_timeout': '设置屏幕变暗前的等待时间',
    'mdesc_browser_ledbright': '更改LED亮度',
    'mdesc_ingame_cheats': '启动时是否开启金手指。可用游戏内快捷键切换',
    'mdesc_ingame_shortreset': '按重置键时的去向。文件夹/ROM:回到上次游戏所在的文件夹。按压时长:短按重置游戏，长按回到该ROM。',
    'mdesc_ingame_enable': '游戏内菜单、即时存档、游戏内快捷键及修改游戏内存的金手指都需要开启此项',
    'mdesc_ingame_pad2': '2号端口的手柄也可使用游戏内快捷键。每次中断会略微增加耗时。',
    'mdesc_ingame_buttons': '启用游戏内快捷键（重置、开关金手指{127}{128}）。需开启游戏内钩子。',
    'mdesc_ingame_cheat_overlay': '游戏内菜单（按住L+R+Y+左）：金手指、即时存档、存档和攻略。需开启游戏内钩子。少数特殊芯片游戏不可用。',
    'mdesc_ingame_holdoff': '启用钩子前等待10秒（帮助部分游戏在开启钩子时正常启动）',
    'mdesc_ingame_savestate': '启用游戏内即时存档并选择手柄。默认：存档 Start+R / 读档 Start+L',
    'mdesc_savestate_slots': '启用即时存档栏位。Select+方向键：每个方向对应一个栏位',
    'mdesc_loadstate_delay': '调整即时读档的延迟（帧）',
    'mdesc_sgb_enable_hooks': '游戏内快捷键需要开启此项',
    'mdesc_sgb_enable_state': '启用SGB2内置的即时存档（XR、XL）',
    'mdesc_sgb_enh_override': '停用/启用SGB增强功能',
    'mdesc_sgb_spr_increase': '增加可同时显示的精灵数量',
    'mdesc_sgb_volume_boost': 'SGB音量过小时可提高音量',
    'mdesc_sgb_clock': '调整SGB时钟（时序）',
    'mdesc_sgb_bios': '选择SGB固件/BIOS版本',
    'mdesc_gbc_mode': 'Game Boy游戏使用的核心：SGB或GBC。仅限Mk.III',
    'mdesc_gbc_sync': 'Genlock：画面流畅。精确：原机速度，可能跳帧。仅限Mk.III',
    'mdesc_gbc_stretch': '高彩画面拉伸至256x192。仅限Mk.III',
    'mdesc_ingame_regionpatch': '绕过游戏的简单区域检测',
    'mdesc_ingame_1chiptransientfixes': '修补亮度变化，修正1CHIP/Jr.主机上的同步错误、扫描线褪色和阴影缺失',
    'mdesc_ingame_brightlimit': '限制整体亮度（如让1CHIP主机符合RGB电平）',
    'mdesc_ingame_resetpatch': '启用重置补丁以对齐时钟。可修正部分游戏的画面问题',
    'mdesc_ingame_autosave': '存档RAM内容变化时自动保存SRM文件',
    'mdesc_ingame_autosave_msu1': 'MSU-1：在合适时机自动保存SRM文件。可能造成短暂卡顿。',
    'mdesc_chip_cx4_speed': '设置Cx4软核速度',
    'mdesc_chip_cc_time_limit': "Campus Challenge '92 / PowerFest '94的回合计时",
    'mdesc_chip_gsu_speed': '设置SuperFX软核速度',
    'mdesc_chip_msu1_volume_boost': 'sd2snes的MSU1音量过小时可提高音量（Rev. E-G）',
    'mdesc_a26_width': 'Atari 2600画面宽度：160为原生1:1，256填满屏幕',
    'mdesc_cx4_speed_fast': '以最快速度运行',
    'mdesc_cx4_speed_normal': '以接近原机的速度运行',
    'mdesc_gsu_speed_fast': '以最快速度运行',
    'mdesc_gsu_speed_normal': '以接近原机的速度运行',
    'text_filesel_selected_file': '所选文件',
    'text_filesel_context_add_to_favorites': '加入收藏',
    'mdesc_filesel_context_add_to_favorites': '将所选文件加入收藏',
    'text_filesel_context_remove_from_favorites': '取消收藏',
    'mdesc_filesel_context_remove_from_favorites': '将所选文件从收藏中移除',
    'text_recent_context_remove_from_recent': '从最近游戏中移除',
    'mdesc_recent_context_remove_from_recent': '将所选文件从最近游戏列表中移除',
    'text_filesel_set_as_autoboot': '设为自动启动',
    'mdesc_filesel_set_as_autoboot': '下次开机时自动启动此ROM（开机/重置时按住START可取消）',
    'text_filesel_set_as_bgm': '设为菜单音乐',
    'mdesc_filesel_set_as_bgm': '将此SPC用作菜单背景音乐',
    'text_filesel_context_delete_file': '删除',
    'mdesc_filesel_context_delete_file': '删除所选文件',
    'text_filesel_context_delete_srm': '删除存档',
    'mdesc_filesel_context_delete_srm': '删除此ROM的SRM存档文件',
    'text_filesel_context_cheats': '金手指',
    'mdesc_filesel_context_cheats': '查看、开启或关闭此ROM的YAML文件中的金手指',
    'text_filesel_context_gameinfo': '游戏信息',
    'mdesc_filesel_context_gameinfo': '开始游戏前显示此ROM的信息画面（封面、截图和资料）',
    'text_cheat_yes': '是 ',
    'text_cheat_no': '否 ',
    'text_cheat_none_title': '金手指',
    'text_ce_name': '名称',
    'text_cheat_none_msg': '未找到此ROM的金手指',
    'text_confirm_delete_file': '删除此文件？',
    'text_confirm_delete_srm': '删除存档文件？',
    'text_confirm_hint': 'A:确认  B:取消',
    'text_confirm_no_sel': '[否]',
    'text_confirm_no_unsel': ' 否 ',
    'text_confirm_yes_sel': '[是]',
    'text_confirm_yes_unsel': ' 是 ',
    'text_statusbar_play': 'A:开始 B:返回 X:菜单',
    'text_statusbar_keys': 'A:选择 B:返回 X:菜单 Y:快捷菜单',
    'text_statusbar_spc': 'B:返回',
    'text_statusbar_menu': 'A:选择 B:返回',
    'text_last': '最近游戏',
    'text_favorite': '收藏游戏',
    'text_no_last': '没有最近游戏',
    'text_no_favorite': '没有收藏游戏',
    'text_favorites_full': '收藏列表已满',
    'text_err_supplfile': '找不到所需文件:',
    'text_err_noimpl': '不支持此芯片:',
    'text_err_nohw': '需要Mk.III硬件:',
    'text_err_generic': '载入错误:',
    'text_exp_title': '*实验性*核心',
    'text_exp_l1': '此核心仍在开发中：',
    'text_exp_l2': '- 可能运行缓慢，并出现声音和',
    'text_exp_l3': '  画面错误',
    'text_exp_l4': '- 部分游戏可能无法运行',
    'text_exp_l5': '- 即时存档和游戏内菜单',
    'text_exp_l6': '  暂时无法使用',
    'text_exp_start': '开始',
    'text_exp_back': '返回',
    'text_exp_nowarn': '开始，以后不再提示',
    'text_on_p1': '开(1P)',
    'text_on_p2': '开(2P)',
    'text_on': '开',
    'text_off': '关',
    'text_15_max': '15(最大)',
    'text_theme': '主题',
    'text_cover_large': '大',
    'text_cover_small': '小',
    'text_gameinfo_context': '快捷菜单',
    'text_nav_folder': '文件夹',
    'text_nav_rom': 'ROM',
    'text_nav_duration': '按压时长',
    'text_enabled': '已启用',
    'text_disabled': '已停用',
    'text_normal': '正常',
    'text_fast': '快速',
    'text_a26_w256': '256(宽)',
    'text_rtc': '实时',
    'text_custom': '自定义',
    'text_yes': '是',
    'text_no': '否',
    'text_onbg_question': '要观看新功能导览吗？',
    'text_onbg_lang': '语言:',
    'text_onbg_hint': '(A) 是        (B) 否',
    'text_auto': '自动',
    'text_gbc_prefer_sgb': '优先SGB',
    'text_gbc_prefer_gbc': '优先GBC',
    'text_gbc_genlock': 'Genlock',
    'text_gbc_exact': '精确',
    'text_add': '添加',
    'text_remove': '删除',
    'text_edit': '编辑',
    'text_save': '保存',
    'text_1min': '1分钟',
    'text_2min': '2分钟',
    'text_3min': '3分钟',
    'text_4min': '4分钟',
    'text_5min': '5分钟',
    'text_10min': '10分钟',
    'text_15min': '15分钟',
    'text_20min': '20分钟',
    'text_30min': '30分钟',
    'text_45min': '45分钟',
    'text_60min': '1小时',
    'text_spcplay': 'SPC音乐播放器',
    'text_spcload': '正在将SPC数据载入SPC700{127}{128}',
    'text_spcstarta': '**** 正在播放SPC乐曲 ****',
    'text_spcstartb': '名称: ',
    'text_spcstartc': '曲目: ',
    'text_spcstartd': '作者: ',
    'text_spc_statusbar': 'B:返回',
    'text_loading': '载入中{127}{128}                        ',
    'text_saving': '保存中{127}{128}                        ',
    'text_cheat': '金手指: ',
    'text_cheat_noname': '(无名称)',
    'text_igm_cheat_noname': '(无名称)',
    'text_igm_cheat_on': '开',
    'text_igm_cheat_off': '关',
    'text_igm_ch_none': '没有金手指',
    'text_igm_ft_tab': '<>:标签 L/R:首尾 A:打开 SEL:帮助 B:关闭',
    'text_igm_ft_cheats': 'A:开关 Y:编辑 SEL:添加 X:金手指 B:返回',
    'text_igm_ft_generic': 'A:选择 B:返回',
    'text_igm_master_on': '金手指: 开',
    'text_igm_master_off': '金手指: 关',
    'text_igm_ft_ce_edit': 'A:编辑 SEL:添加代码 Y:删除 B:返回',
    'text_igm_ft_ce_kbd': 'A:输入 Y:退格 SEL:空格 X:确定 B:取消',
    'text_igm_ft_help': 'B:返回 START:关闭',
    'text_igm_ce_title_new': '新建金手指',
    'text_igm_ce_title_edit': '编辑金手指',
    'text_igm_ce_name': '名称:',
    'text_igm_ce_save': '保存',
    'text_igm_ce_delete': '删除金手指',
    'text_igm_ce_confirm': '删除此金手指？',
    'text_igm_ce_confirm_keys': 'A:是  B:否',
    'text_igm_ce_nosup': '请更新固件',
    'text_igm_ce_full': '金手指列表已满',
    'text_igm_ce_badcode': '代码无效',
    'text_si_fw': '    固件版本: {2}',
    'text_si_busy': '正在计算磁盘空间{127}{128}',
    'text_si_removed': '    *** SD卡已移除/USB忙碌 ***',
    'text_si_maker': 'SD制造商/OEM:       0x{3}, {34}{4}{34}',
    'text_si_product': 'SD产品名称/版本:   {34}{5}{34}, v{6}.{7}',
    'text_si_serial': 'SD序列号/生产日期: {8}, {9}/{10}',
    'text_si_acc': 'SD访问时间(平均/最大): {11}.{12}/{13}.{14}ms',
    'text_si_accmeas': 'SD访问时间: 测量中{127}{128}',
    'text_si_usage': 'SD卡已用空间: {15}MB / {16}MB',
    'text_si_sgb': 'sgb{17}_boot.bin/sgb{17}_snes.bin: {18}',
    'text_si_sgb_checking': '检查中{127}{128}',
    'text_si_sgb_missing': '缺失',
    'text_si_sgb_mismatch': '不匹配',
    'text_si_sgb_ok': '正常',
    'text_si_cic': 'CIC状态: {19}',
    'text_si_clk': 'SNES主时钟: {20}Hz',
    'text_si_clkmeas': 'SNES主时钟: 测量中{127}{128}',
    'text_si_u16on': 'Ultra16序列号(自动启动:开): {21}',
    'text_si_u16off': 'Ultra16序列号(自动启动:关): {21}',
    'text_si_model': '型号: {22}',
    'text_si_updatefw': '*** 请更新固件 ***',
    'mtext_mm_memtest': '内存测试',
    'mdesc_mm_memtest': '先检查FPGA与RAM的连线，再逐一检查每个存储单元（约30秒）。测试会重置主机。',
    'text_mtl_prompt': 'A:开始测试  B:关闭',
    'text_mtl_prompt2': '测试会重置主机，约需30秒。',
    'text_mtl_run': '正在测试内存，请稍候{127}{128}',
    'text_mtl_none': '尚未进行测试。',
    'text_mtl_pass': '所有RAM线路正常。',
    'text_mtl_fail': '发现故障:',
    'text_mtl_nocore': '/sd2snes/fpga_test缺失或损坏。',
    'text_mtl_more': '(其余故障未显示)',
    'text_mtl_cellpass': '所有存储单元验证通过。',
    'text_mtl_cellfail': '首个故障单元地址: 0x',
    'text_mtl_cellskip': '已跳过单元扫描:请先修复连线。',
    'text_mt_data': '检查数据线 D',
    'text_mt_addr': '检查地址线 A',
    'text_mt_short': '疑似短路 A',
    'text_mt_bytesel': '检查 LB# / UB#',
    'text_mt_ctrl': '检查 CE# / OE# / WE#',
    'text_mt_fpgactrl': '检查 FPGA CE# / OE# / WE#',
    'text_pcm_title': 'PCM播放器',
    'text_pcm_prompt': 'A:播放/暂停  B:关闭',
    'text_pcm_promptb': 'B:关闭',
    'text_pcm_paused': '已暂停',
    'text_pcm_erropen': '无法读取此文件。',
    'text_pcm_errmagic': '不是MSU-1 PCM文件。',
    'text_pcm_nosup': '*** 请更新固件 ***',
    'text_st_slotb_title': 'Sufami Turbo - 卡槽B',
    'text_st_slotb_footer': 'A:开始  B:返回  <>:翻页  LR:首尾',
    'text_st_slotb_none': '[卡槽B不插卡带]',
    'text_ips_nopatch': '[不使用补丁]',
    'text_ips_header': '补丁',
    'text_patch_hdr_auto': '自动 ',
    'text_patch_hdr_on': '带头 ',
    'text_patch_hdr_off': '无头 ',
    'text_patch_footer': 'A:开始  Y:更多  B:返回  <>:翻页  LR:首尾',
    'text_patch_creating': '正在生成补丁版ROM...',
    'text_err_patchexport': '无法写入补丁版ROM',
    'text_patch_export_ok': '补丁版ROM已生成',
    'text_patch_export_part': 'ROM已生成，附属文件不完整',
    'text_patch_export_exists': '补丁版ROM已存在',
    'text_patch_hdrsel_auto': '自动(检测)',
    'text_patch_hdrsel_on': '带文件头',
    'text_patch_hdrsel_off': '无文件头',
    'mtext_patch_header_mode': '文件头模式',
    'mdesc_patch_header_mode': 'IPS偏移量的读取方式：自动、带文件头（偏移512字节）或无文件头。',
    'mtext_patch_create_rom': '生成补丁版ROM',
    'mdesc_patch_create_rom': '在原ROM旁写入打好补丁的ROM，以补丁文件命名，并一并复制封面、存档、金手指和攻略。需要几分钟。',
    'cheat_tab_head': '说明                                      启用',
    'cheat_tab_hint_text': ' A:开关  Y:编辑  Sel:添加  B:退出',
    'mtext_browser_showcov': '显示封面',
    'mdesc_browser_showcov': '在菜单中显示游戏封面',
    'mtext_browser_covlists': ' {129}收藏和最近游戏',
    'mdesc_browser_covlists': '在最近游戏和收藏列表中也显示封面',
    'mtext_browser_menumusic': '菜单音乐',
    'mtext_browser_menumusic_random': ' {129}随机音乐',
    'mtext_browser_menusfx': '菜单音效',
    'mtext_browser_text_outline': '文字描边',
    'mtext_browser_text_aa': '文字抗锯齿',
    'mdesc_browser_menumusic': '在菜单中播放背景音乐（menu.spc）',
    'mtext_browser_sortfav': '收藏排序',
    'mdesc_browser_sortfav': '按字母顺序排列收藏列表',
    'mtext_browser_restoretheme': '恢复默认主题',
    'mdesc_browser_restoretheme': '将菜单主题恢复为内置默认主题',
    'mtext_browser_restoreclassic': '恢复经典主题',
    'mdesc_browser_restoreclassic': '载入经典sd2snes外观（卡上需有/sd2snes/classic.thm）',
    'mtext_browser_restoremusic': '恢复默认音乐',
    'mdesc_browser_restoremusic': '将菜单背景音乐恢复为默认（menu.spc）',
    'mdesc_browser_menumusic_random': '每次载入时从音乐文件夹随机选一首.spc',
    'mdesc_browser_text_outline': '菜单文字的深色描边：跟随主题，或强制开/关',
    'mdesc_browser_text_aa': '菜单文字的边缘平滑：跟随主题，或强制开/关',
    'text_mm_language': '语言',
    'mdesc_mm_language': '设置菜单/固件的语言',
    'mdesc_browser_menusfx': '浏览菜单时播放音效',
    'mtext_browser_gameinfo': '游戏信息',
    'mtext_gameinfo_enable': '显示信息画面',
    'mdesc_browser_gameinfo': '启动在/sd2snes/info中有资料的ROM前，显示封面、截图和信息',
    'mdesc_cfg_gameinfo': '游戏启动前信息画面的选项',
    'mtext_browser_gameinfo_video': ' {129}显示视频',
    'mdesc_browser_gameinfo_video': '在游戏信息画面播放动态片段（关闭时显示静态截图）',
    'mtext_browser_gameinfo_music': ' {129}播放视频音乐',
    'mdesc_browser_gameinfo_music': '片段显示时播放其配乐。需先开启显示视频。',
    'text_gi_developer': '开发商',
    'text_gi_publisher': '发行商',
    'text_gi_year': '年份',
    'text_gi_players': '人数',
    'text_gi_genre': '类型',
    'text_gi_chip': '芯片',
    'text_gi_footer': 'A:开始  B:返回  Y:简介  Sel:金手指',
    'text_gi_footer_nav': 'A:开始 B:返回 Y:简介 Sel:金手指 {241}{242}:切换游戏',
    'text_gi_footer_full': 'B:返回  上下:滚动',
    'text_gi_footer_man': 'A:开始 B:返回 Y:简介 X:攻略 Sel:金手指',
    'text_gi_footer_nav_man': 'A:开始 B:返回 Y:简介 X:攻略 Sel:金手指 {241}{242}:切换',
    'text_gi_footer_pick': 'A:打开  B:返回',
    'text_gi_slug_manual': '说明书',
    'text_gi_slug_guide': '攻略',
    'text_gi_slug_map': '地图',
    'text_gi_slug_insert': '插页',
    'text_gi_slug_other': '其他',
}
