"""Spanish (Español) strings for the sd2snes menu.

Maps const.a65 string labels -> es text. Accented chars are written as real
UTF-8 here; build_const.py encodes them to the font byte codes.
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
mdesc_* item descriptions ARE rendered now (the selected option's help box) and
localized like the rest; the pool lives in bank $C1 (see build_const.py).
"""

TRANSLATIONS = {
    'text_clkset': 'Ajuste la hora',
    'text_mainmenu': 'Menú Principal',
    'text_mm_file': 'Navegador de Archivos',
    'text_mm_last': 'Juegos Recientes',
    'text_mm_favorites': 'Juegos Favoritos',
    'mtext_mm_cfg': 'Configuración',
    'mtext_mm_sysinfo': 'Información del Sistema',
    'mtext_cfg_time': 'Ajustar Reloj',
    'mtext_cfg_bsx': 'Opciones BS-X',
    'mtext_cfg_browser': 'Opciones del Navegador',
    'mtext_cfg_chip': 'Opciones de Chip',
    'mtext_cfg_sgb': 'Opciones SGB',
    'mtext_cfg_ingame': 'Opciones en Juego',
    'mtext_cfg_savestates': 'Opciones de Savestates',
    'mtext_cfg_scic': 'Opciones SuperCIC',
    'mtext_cfg_patch': 'Opciones de Patches',
    'mtext_patch_verify': 'Verificar Integridad (~23s)',
    'mtext_cfg_wifi_en': 'Activar WiFi',
    'mdesc_cfg_wifi_en': 'Activa/desactiva el companion WiFi (apagado: sin punto de acceso, sin WebUI)',
    'mdesc_cfg_wifi': 'Conectar el sd2snes a una red WiFi',
    'wifi_s_scan': 'Buscando redes...',
    'wifi_s_nonet': 'No se encontraron redes.',
    'wifi_s_hint': 'arr/aba  A:elegir  X:rescan  B:volver',
    'wifi_s_curconn': 'Conectado: ',
    'wifi_s_curoff': 'No conectado',
    'wifi_s_passlbl': 'Contraseña:',
    'wifi_s_kbd1': 'A:teclear B:borrar X:espacio Y:aA',
    'wifi_s_kbd2': 'START:conectar  SELECT:volver',
    'wifi_s_connecting': 'Conectando...',
    'wifi_s_ok': 'Conectado!',
    'wifi_s_anykey': 'Pulsa cualquier botón para volver',
    'wifi_s_fail': 'Fallo - revisa la clave. A:reintentar',
    'mtext_bsx_timesource': 'Reloj BS-X',
    'mtext_bsx_time': 'Hora personalizada',
    'mtext_scic_enable': 'Activar SuperCIC',
    'mtext_scic_vmode_menu': ' {129}Modo vídeo menú',
    'mtext_scic_vmode_game': ' {129}Modo vídeo juego',
    'mtext_browser_sort': 'Ordenar directorios',
    'mtext_browser_hide_ext': 'Ocultar extensiones',
    'mtext_browser_screensaver': 'Protector de pantalla',
    'mtext_browser_screensaver_timeout': 'Atenuar pantalla tras',
    'mtext_browser_ledbright': 'Brillo de los LEDs',
    'mtext_ingame_cheats': 'Iniciar con trucos',
    'mtext_ingame_shortreset': 'Reset al menú',
    'mtext_ingame_enable': 'Hook en juego',
    'mtext_ingame_buttons': ' {129}Botones en juego',
    'mtext_ingame_cheat_overlay': ' {129}Menú de trucos',
    'mtext_ingame_holdoff': ' {129}Espera inicial',
    'mtext_ingame_savestate': 'Savestates en juego',
    'mtext_savestate_slots': ' {129}Ranuras de savestate',
    'mtext_loadstate_delay': ' {129}Retardo de carga',
    'mtext_sgb_enable_hooks': 'Hooks en juego',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'Funciones SGB',
    'mtext_sgb_spr_increase': 'Límite máx. sprites (40)',
    'mtext_sgb_volume_boost': 'Aumento de volumen',
    'mtext_sgb_clock': 'Clock (Timing)',
    'mtext_sgb_bios': 'Versión del BIOS',
    'mtext_ingame_regionpatch': 'Patch auto. de región',
    'mtext_ingame_1chiptransientfixes': 'Correcciones 1CHIP',
    'mtext_ingame_brightlimit': 'Límite de brillo',
    'mtext_ingame_resetpatch': 'Patch de reset (clock)',
    'mtext_ingame_autosave': 'Autoguardado',
    'mtext_ingame_autosave_msu1': ' {129}Autoguardado MSU-1',
    'mtext_chip_cx4_speed': 'Velocidad Cx4',
    'mtext_chip_gsu_speed': 'Velocidad SuperFX',
    'mtext_chip_msu1_volume_boost': 'Aumento volumen MSU-1',
    'mdesc_mm_last': 'Muestra hasta 10 juegos recientes',
    'mdesc_mm_favorites': 'Muestra hasta 20 juegos favoritos',
    'mdesc_mm_cfg': 'Configurar el sd2snes',
    'mdesc_mm_sysinfo': 'Info de FW, SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Ajustar fecha y hora',
    'mdesc_cfg_bsx': 'Opciones específicas BS-X/Satellaview',
    'mdesc_cfg_browser': 'Cambiar opciones del navegador',
    'mdesc_cfg_chip': 'Funciones especiales de chip',
    'mdesc_cfg_ingame': 'Funciones durante el juego',
    'mdesc_cfg_sgb': 'Funciones del Super Game Boy',
    'mdesc_cfg_savestates': 'Funciones de savestates',
    'mdesc_cfg_scic': 'Activar SuperCIC y modos de vídeo',
    'mdesc_cfg_patch': 'Opciones de parcheo IPS/BPS',
    'mdesc_patch_verify': 'Relee la ROM parcheada para verificarla (carga mucho más lenta)',
    'mdesc_bsx_timesource': 'Fecha/hora que ven los juegos BS-X',
    'mdesc_bsx_time': 'Hora y fecha personalizadas para BS-X',
    'mdesc_scic_enable': 'Necesario para funciones SuperCIC',
    'mdesc_scic_vmode_menu': 'Modo de vídeo del menú',
    'mdesc_scic_vmode_game': 'Modo de vídeo de los juegos',
    'mdesc_browser_sort': 'Ordenar listas de archivos',
    'mdesc_browser_hide_ext': 'Ocultar extensiones de archivos',
    'mdesc_browser_screensaver': 'Oscurecer la pantalla tras un tiempo',
    'mdesc_browser_screensaver_timeout': 'Tiempo para oscurecer la pantalla',
    'mdesc_browser_ledbright': 'Cambiar brillo de los LEDs',
    'mdesc_ingame_cheats': 'Iniciar con trucos activados. Se puede cambiar con los botones en juego',
    'mdesc_ingame_shortreset': 'Volver al menú con reset corto (Des/Act/Carpeta/ROM). Carpeta: vuelve a la última carpeta. ROM: además preselecciona la ROM.',
    'mdesc_ingame_enable': 'Necesario para botones en juego y trucos 7E/7F',
    'mdesc_ingame_buttons': 'Botones en juego (reset, activar/desactivar trucos{127}{128}). Requiere el hook activado.',
    'mdesc_ingame_cheat_overlay': 'Menú de trucos en juego (manten L+R+Y+Izq) para activarlos al vuelo. Requiere hook. No funciona con chips especiales.',
    'mdesc_ingame_holdoff': 'Espera 10 segundos antes de activar el hook (ayuda a algunos juegos a arrancar con el hook activado)',
    'mdesc_ingame_savestate': 'Activar savestates en juego y elegir mando. Predet.: Guardar - Start+R / Cargar - Start+L',
    'mdesc_savestate_slots': 'Activar ranuras de savestate. Select+Dpad: cada dirección es una ranura',
    'mdesc_loadstate_delay': 'Ajustar el retardo de carga de estado (frames)',
    'mdesc_sgb_enable_hooks': 'Necesario para los botones en juego',
    'mdesc_sgb_enable_state': 'Activar savestates internos en SGB2 (XR, XL)',
    'mdesc_sgb_enh_override': 'Desactivar/activar las mejoras SGB',
    'mdesc_sgb_spr_increase': 'Aumentar el número de sprites visibles',
    'mdesc_sgb_volume_boost': 'Aumentar volumen del audio SGB si es muy bajo',
    'mdesc_sgb_clock': 'Ajusta el clock del SGB (timing)',
    'mdesc_sgb_bios': 'Seleccionar una versión de firmware/BIOS del SGB',
    'mdesc_ingame_regionpatch': 'Evita la protección simple de región de los juegos',
    'mdesc_ingame_1chiptransientfixes': 'Corrige glitches de brillo, líneas y sombras en consolas 1CHIP/Jr.',
    'mdesc_ingame_brightlimit': 'Limitar el brillo general (p. ej. en consolas 1CHIP para niveles RGB)',
    'mdesc_ingame_resetpatch': 'Activar patch de reset para alinear clocks. Corrige fallos gráficos en algunos juegos',
    'mdesc_ingame_autosave': 'Guardar SRM automáticamente cuando cambia la Save RAM',
    'mdesc_ingame_autosave_msu1': 'MSU-1: aprovecha pausas para autoguardar SRM. Puede causar breves cortes.',
    'mdesc_chip_cx4_speed': 'Velocidad del soft core Cx4',
    'mdesc_chip_gsu_speed': 'Velocidad del soft core SuperFX',
    'mdesc_chip_msu1_volume_boost': 'Aumento de volumen MSU-1 si tu sd2snes suena muy bajo (Rev. E-G)',
    'mdesc_cx4_speed_fast': 'Ejecutar lo más rápido posible',
    'mdesc_cx4_speed_normal': 'Ejecutar aprox. a la velocidad original',
    'mdesc_gsu_speed_fast': 'Ejecutar lo más rápido posible',
    'mdesc_gsu_speed_normal': 'Ejecutar aprox. a la velocidad original',
    'text_filesel_selected_file': 'Archivo seleccionado',
    'text_filesel_context_add_to_favorites': 'Añadir a favoritos',
    'mdesc_filesel_context_add_to_favorites': 'Añade el archivo seleccionado a favoritos',
    'text_filesel_context_remove_from_favorites': 'Quitar de favoritos',
    'mdesc_filesel_context_remove_from_favorites': 'Quita el archivo seleccionado de favoritos',
    'text_recent_context_remove_from_recent': 'Quitar de recientes',
    'mdesc_recent_context_remove_from_recent': 'Quita el archivo de la lista de recientes',
    'text_filesel_set_as_autoboot': 'Definir como autoboot',
    'mdesc_filesel_set_as_autoboot': 'Arranca esta ROM en el próximo encendido (mantén START para cancelar)',
    'text_filesel_set_as_bgm': 'Definir como música del menú',
    'mdesc_filesel_set_as_bgm': 'Usar este SPC como música de fondo del menú',
    'text_filesel_context_delete_file': 'Eliminar',
    'mdesc_filesel_context_delete_file': 'Elimina el archivo seleccionado',
    'text_filesel_context_delete_srm': 'Eliminar save',
    'mdesc_filesel_context_delete_srm': 'Elimina el archivo de save SRM para esta ROM',
    'text_filesel_context_cheats': 'Trucos',
    'mdesc_filesel_context_cheats': 'Visualizar, activar o desactivar trucos del archivo YAML de esta ROM',
    'text_cheat_yes': 'Sí',
    'text_cheat_no': 'No',
    'text_cheat_none_title': 'Trucos',
    'text_cheat_none_msg': 'No hay trucos para esta ROM',
    'text_confirm_delete_file': '¿Borrar este archivo?',
    'text_confirm_delete_srm': '¿Borrar el archivo de guardado?',
    'text_confirm_hint': 'A:Confirmar  B:Cancelar',
    'text_confirm_no_sel': '[No]',
    'text_confirm_no_unsel': ' No ',
    'text_confirm_yes_sel': '[Sí]',
    'text_confirm_yes_unsel': ' Sí ',
    'text_statusbar_play': 'A:Jugar B:Atrás X:Menú',
    'text_statusbar_keys': 'A:OK B:Atrás X:Menú Y:Contexto',
    'text_statusbar_spc': 'B:Atrás',
    'text_statusbar_menu': 'A:OK B:Atrás',
    'text_last': 'Juegos recientes',
    'text_favorite': 'Juegos favoritos',
    'text_no_last': 'Sin recientes',
    'text_no_favorite': 'Sin favoritos',
    'text_favorites_full': 'Favoritos lleno',
    'text_err_supplfile': 'Archivo no hallado:',
    'text_err_noimpl': 'Chip no soportado:',
    'text_err_generic': 'Error al cargar:',
    'text_on_p1': 'Sí: P1',
    'text_on_p2': 'Sí: P2',
    'text_on': 'Sí',
    'text_off': 'No',
    'text_cover_large': 'Grande',
    'text_cover_small': 'Pequeño',
    'text_nav_folder': 'Carpeta',
    'text_nav_rom': 'ROM',
    'text_enabled': 'Activo',
    'text_disabled': 'Inactivo',
    'text_normal': 'Normal',
    'text_fast': 'Rápido',
    'text_rtc': 'Tiempo real',
    'text_custom': 'Person.',
    'text_yes': 'Sí',
    'text_no': 'No',
    'text_auto': 'Auto',
    'text_add': 'Añadir',
    'text_remove': 'Quitar',
    'text_edit': 'Editar',
    'text_save': 'Guardar',
    'text_1min': '1 min',
    'text_2min': '2 min',
    'text_3min': '3 min',
    'text_4min': '4 min',
    'text_5min': '5 min',
    'text_10min': '10 min',
    'text_15min': '15 min',
    'text_20min': '20 min',
    'text_30min': '30 min',
    'text_45min': '45 min',
    'text_60min': '1 hora',
    'text_spcplay': 'Reproductor de SPC',
    'text_spcload': 'Cargando SPC en SPC700{127}{128}    ',
    'text_spcstarta': '**** Reproduciendo SPC ****',
    'text_spcstartb': 'Nombre:',
    'text_spcstartc': 'Canción:',
    'text_spcstartd': 'Artista:',
    'text_spc_statusbar': 'B:Atrás',
    'text_loading': 'Cargando{127}{128}                       ',
    'text_saving': 'Guardando{127}{128}                      ',
    'text_cheat': 'Trucos para ',
    'text_ips_nopatch': '[Sin patch]',
    'text_ips_header': 'Parches',
    'cheat_tab_head': 'Nombre                                    Activo',
    'cheat_tab_hint_text': ' A:Hab./Desh.   B:Guardar & Salir ',
    'mtext_browser_showcov': 'Mostrar carátulas',
    'mdesc_browser_showcov': 'Mostrar las carátulas de los juegos en el menú',
    'mtext_browser_covlists': ' {129}Favoritos/Recientes',
    'mdesc_browser_covlists': 'Mostrar carátulas también en las listas Recientes y Favoritos',
    'mtext_browser_menumusic': 'Música del menú',
    'mtext_browser_menusfx': 'Sonidos del menú',
    'mdesc_browser_menumusic': 'Reproducir música de fondo (menu.spc) en el menú',
    'mtext_browser_sortfav': 'Ordenar favoritos',
    'mdesc_browser_sortfav': 'Ordenar la lista de favoritos alfabéticamente',
    'mtext_browser_restoretheme': 'Restaurar tema',
    'mdesc_browser_restoretheme': 'Restaurar el tema del menú al predeterminado',
    'mtext_browser_restoremusic': 'Restaurar música',
    'mdesc_browser_restoremusic': 'Restaurar la música del menú al predeterminado (menu.spc)',
    'text_mm_language': 'Idioma',
    'mdesc_mm_language': 'Definir el idioma del menú/firmware',
    'mdesc_browser_menusfx': 'Reproducir efectos de sonido al navegar por el menú',
    'mtext_browser_gameinfo': 'Info del Juego',
    'mdesc_browser_gameinfo': 'Muestra carátula, captura e info antes de iniciar una ROM que tenga una entrada en /sd2snes/info',
    'mtext_browser_gameinfo_video': ' {129}Mostrar vídeo',
    'mdesc_browser_gameinfo_video': 'Reproduce el clip animado en la ficha (apagado muestra una captura estática)',
    'mtext_browser_gameinfo_music': ' {129}Música del vídeo',
    'mdesc_browser_gameinfo_music': 'Reproduce la música del vídeo mientras se muestra el clip. Requiere Mostrar vídeo.',
    'text_gi_developer': 'Desarrollador',
    'text_gi_year': 'Año',
    'text_gi_players': 'Jugadores',
    'text_gi_genre': 'Género',
    'text_gi_chip': 'Chip',
    'text_gi_footer': 'A: Jugar  B: Volver  Y: Descripción',
    'text_gi_footer_nav': 'A:Jugar B:Volver Y:Desc Arr/Abj:Juego',
    'text_gi_footer_full': 'B: Volver  Arriba/Abajo: Desplazar',
}
