"""German (Deutsch) strings for the sd2snes menu.

Maps const.a65 string labels -> de text. The current menu font lacks some
German glyphs, so those characters are written as ae/oe/ue/ss for predictable rendering.
Placeholders: {129}=submenu icon, {127}{128}=ellipsis control bytes.
mdesc_* item descriptions are NOT rendered by the current menu (build_const
skips them), so they stay English at build time and cost no ROM space.
"""

TRANSLATIONS = {
    'text_clkset': 'Bitte Uhrzeit einstellen',
    'text_mainmenu': 'Hauptmenue',
    'text_mm_file': 'Dateibrowser',
    'text_mm_last': 'Letzte Spiele',
    'text_mm_favorites': 'Favoriten',
    'mtext_mm_cfg': 'Einstellungen',
    'mtext_mm_sysinfo': 'Systeminfo',
    'mtext_cfg_time': 'Uhr stellen',
    'mtext_cfg_bsx': 'BS-X Optionen',
    'mtext_cfg_browser': 'Browser-Optionen',
    'mtext_cfg_chip': 'Chip-Optionen',
    'mtext_cfg_sgb': 'SGB Optionen',
    'mtext_cfg_ingame': 'Im-Spiel Optionen',
    'mtext_cfg_savestates': 'Savestate-Optionen',
    'mtext_cfg_scic': 'SuperCIC Optionen',
    'mtext_cfg_patch': 'Patch-Optionen',
    'mtext_patch_verify': 'Integritaet pruefen (~23s)',
    'mtext_cfg_wifi_en': 'WLAN aktivieren',
    'mtext_bsx_timesource': 'BS-X Uhr',
    'mtext_bsx_time': 'Eigene Zeit',
    'mtext_scic_enable': 'SuperCIC aktivieren',
    'mtext_scic_vmode_menu': ' {129}Video-Modus Menue',
    'mtext_scic_vmode_game': ' {129}Video-Modus Spiel',
    'mtext_browser_sort': 'Ordner sortieren',
    'mtext_browser_hide_ext': 'Endungen ausblenden',
    'mtext_browser_screensaver': 'Bildschirmschoner',
    'mtext_browser_screensaver_timeout': 'Abdunkeln nach',
    'mtext_browser_ledbright': 'LED-Helligkeit',
    'mtext_ingame_cheats': 'Mit Cheats starten',
    'mtext_ingame_shortreset': 'Reset zum Menue',
    'mtext_ingame_enable': 'Im-Spiel Hook',
    'mtext_ingame_buttons': ' {129}Im-Spiel Tasten',
    'mtext_ingame_holdoff': ' {129}Start-Wartezeit',
    'mtext_ingame_savestate': 'Im-Spiel Savestates',
    'mtext_savestate_slots': ' {129}Savestate-Slots',
    'mtext_loadstate_delay': ' {129}Ladeverzoegerung',
    'mtext_sgb_enable_hooks': 'Im-Spiel Hooks',
    'mtext_sgb_enable_state': 'Savestates (XR, XL)',
    'mtext_sgb_enh_override': 'SGB Funktionen',
    'mtext_sgb_spr_increase': 'Sprite-Limit (40)',
    'mtext_sgb_volume_boost': 'Lautstaerke-Boost',
    'mtext_sgb_clock': 'Takt (Timing)',
    'mtext_sgb_bios': 'BIOS-Version',
    'mtext_ingame_regionpatch': 'Auto-Regionpatch',
    'mtext_ingame_1chiptransientfixes': '1CHIP Korrekturen',
    'mtext_ingame_brightlimit': 'Helligkeitslimit',
    'mtext_ingame_resetpatch': 'Reset-Patch (Takt)',
    'mtext_ingame_autosave': 'Auto-Speichern',
    'mtext_ingame_autosave_msu1': ' {129}MSU-1 Auto-Speich.',
    'mtext_chip_cx4_speed': 'Cx4 Geschwindigkeit',
    'mtext_chip_gsu_speed': 'SuperFX Geschw.',
    'mtext_chip_msu1_volume_boost': 'MSU-1 Lautstaerke',
    'mdesc_mm_last': 'Zeigt bis zu 10 zuletzt gespielte Spiele',
    'mdesc_mm_favorites': 'Zeigt bis zu 10 Favoriten',
    'mdesc_mm_cfg': 'sd2snes konfigurieren',
    'mdesc_mm_sysinfo': 'Info zu FW, SD, SNES, CIC{127}{128}',
    'mdesc_cfg_time': 'Datum und Uhrzeit einstellen',
    'mdesc_cfg_bsx': 'BS-X/Satellaview-spezifische Optionen',
    'mdesc_cfg_browser': 'Optionen des Dateibrowsers aendern',
    'mdesc_cfg_chip': 'Spezialchip-Funktionen einstellen',
    'mdesc_cfg_ingame': 'Funktionen waehrend des Spiels einstellen',
    'mdesc_cfg_sgb': 'Super Game Boy Funktionen einstellen',
    'mdesc_cfg_savestates': 'Savestate-Funktionen einstellen',
    'mdesc_cfg_scic': 'SuperCIC und Videomodi einstellen',
    'mdesc_cfg_patch': 'Optionen fuer IPS/BPS Patches',
    'mdesc_patch_verify': 'Gepatchte ROM zum Pruefen erneut lesen (deutlich langsamer)',
    'mdesc_bsx_timesource': 'Datum/Uhrzeit fuer BS-X Spiele',
    'mdesc_bsx_time': 'Eigene Uhrzeit und eigenes Datum fuer BS-X',
    'mdesc_scic_enable': 'Noetig fuer SuperCIC-Funktionen',
    'mdesc_scic_vmode_menu': 'Videomodus des Menues',
    'mdesc_scic_vmode_game': 'Videomodus der Spiele',
    'mdesc_browser_sort': 'Dateilisten sortieren',
    'mdesc_browser_hide_ext': 'Dateiendungen ausblenden',
    'mdesc_browser_screensaver': 'Bild nach einer Zeit abdunkeln',
    'mdesc_browser_screensaver_timeout': 'Zeit bis zum Abdunkeln',
    'mdesc_browser_ledbright': 'LED-Helligkeit aendern',
    'mdesc_ingame_cheats': 'Mit aktivierten Cheats starten',
    'mdesc_ingame_shortreset': 'Per kurzem Reset zum Menue zurueck (Aus/Ein/Ordner/ROM).',
    'mdesc_ingame_enable': 'Noetig fuer Im-Spiel Tasten und 7E/7F Cheats',
    'mdesc_ingame_buttons': 'Im-Spiel Tasten (Reset, Cheats{127}{128}). Benoetigt Hook.',
    'mdesc_ingame_holdoff': '10 Sekunden warten, bevor der Hook aktiviert wird',
    'mdesc_ingame_savestate': 'Savestates im Spiel aktivieren',
    'mdesc_savestate_slots': 'Savestate-Slots aktivieren. Select+Dpad waehlt Slot',
    'mdesc_loadstate_delay': 'Loadstate-Verzoegerung einstellen (Frames)',
    'mdesc_sgb_enable_hooks': 'Noetig fuer Im-Spiel Tasten',
    'mdesc_sgb_enable_state': 'Interne Savestates in SGB2 aktivieren (XR, XL)',
    'mdesc_sgb_enh_override': 'SGB-Erweiterungen aus-/einschalten',
    'mdesc_sgb_spr_increase': 'Mehr sichtbare Sprites erlauben',
    'mdesc_sgb_volume_boost': 'SGB-Audio lauter machen',
    'mdesc_sgb_clock': 'SGB-Takt einstellen (Timing)',
    'mdesc_sgb_bios': 'SGB Firmware/BIOS-Version auswaehlen',
    'mdesc_ingame_regionpatch': 'Einfache Regionssperren umgehen',
    'mdesc_ingame_1chiptransientfixes': 'Helligkeitsfehler auf 1CHIP/Jr. korrigieren',
    'mdesc_ingame_brightlimit': 'Gesamthelligkeit begrenzen',
    'mdesc_ingame_resetpatch': 'Reset-Patch fuer Taktausrichtung aktivieren',
    'mdesc_ingame_autosave': 'SRM automatisch speichern, wenn es sich aendert',
    'mdesc_ingame_autosave_msu1': 'MSU-1: SRM in Pausen speichern. Kann kurz stocken.',
    'mdesc_chip_cx4_speed': 'Geschwindigkeit des Cx4 Softcores',
    'mdesc_chip_gsu_speed': 'Geschwindigkeit des SuperFX Softcores',
    'mdesc_chip_msu1_volume_boost': 'MSU-1 Lautstaerke-Boost',
    'mdesc_cx4_speed_fast': 'So schnell wie moeglich ausfuehren',
    'mdesc_cx4_speed_normal': 'Etwa mit Originalgeschwindigkeit ausfuehren',
    'mdesc_gsu_speed_fast': 'So schnell wie moeglich ausfuehren',
    'mdesc_gsu_speed_normal': 'Etwa mit Originalgeschwindigkeit ausfuehren',
    'text_filesel_selected_file': 'Gewaehlte Datei',
    'text_filesel_context_add_to_favorites': 'Zu Favoriten',
    'mdesc_filesel_context_add_to_favorites': 'Datei zu Favoriten hinzufuegen',
    'text_filesel_context_remove_from_favorites': 'Aus Favoriten entfernen',
    'mdesc_filesel_context_remove_from_favorites': 'Datei aus Favoriten entfernen',
    'text_recent_context_remove_from_recent': 'Aus letzten entfernen',
    'mdesc_recent_context_remove_from_recent': 'Datei aus letzter Liste entfernen',
    'text_filesel_set_as_autoboot': 'Als Autoboot setzen',
    'mdesc_filesel_set_as_autoboot': 'Diese ROM beim naechsten Einschalten starten',
    'text_filesel_context_delete_file': 'Loeschen',
    'mdesc_filesel_context_delete_file': 'Gewaehlte Datei loeschen',
    'text_filesel_context_delete_srm': 'Save loeschen',
    'mdesc_filesel_context_delete_srm': 'SRM-Save fuer diese ROM loeschen',
    'text_filesel_context_cheats': 'Cheats',
    'mdesc_filesel_context_cheats': 'Cheats aus der YAML-Datei ansehen oder umschalten',
    'text_cheat_yes': 'Ja ',
    'text_cheat_no': 'Nein',
    'text_cheat_none_title': 'Cheats',
    'text_cheat_none_msg': 'Keine Cheats fuer diese ROM',
    'text_confirm_delete_file': 'Diese Datei loeschen?',
    'text_confirm_delete_srm': 'Save-Datei loeschen?',
    'text_confirm_hint': 'A:Bestaet.  B:Abbruch',
    'text_confirm_no_sel': '[Nein]',
    'text_confirm_no_unsel': 'Nein ',
    'text_confirm_yes_sel': '[Ja]',
    'text_confirm_yes_unsel': ' Ja ',
    'text_statusbar_play': 'A:Spielen B:Zurueck X:Menue',
    'text_statusbar_keys': 'A:OK B:Zurueck X:Menue Y:Kontext',
    'text_statusbar_spc': 'B:Zurueck',
    'text_statusbar_menu': 'A:OK B:Zurueck',
    'text_last': 'Letzte Spiele',
    'text_favorite': 'Favoriten',
    'text_no_last': 'Keine letzten',
    'text_no_favorite': 'Keine Favoriten',
    'text_on_p1': 'Ein: P1',
    'text_on_p2': 'Ein: P2',
    'text_on': 'Ein',
    'text_off': 'Aus',
    'text_cover_large': 'Gross',
    'text_cover_small': 'Klein',
    'text_nav_folder': 'Ordner',
    'text_nav_rom': 'ROM',
    'text_enabled': 'Aktiv',
    'text_disabled': 'Inaktiv',
    'text_normal': 'Normal',
    'text_fast': 'Schnell',
    'text_rtc': 'Echtzeit',
    'text_custom': 'Eigene',
    'text_yes': 'Ja',
    'text_no': 'Nein',
    'text_auto': 'Auto',
    'text_add': 'Hinzuf.',
    'text_remove': 'Entfern.',
    'text_edit': 'Aendern',
    'text_save': 'Speichern',
    'text_1min': '1 min',
    'text_2min': '2 min',
    'text_3min': '3 min',
    'text_4min': '4 min',
    'text_5min': '5 min',
    'text_10min': '10 min',
    'text_15min': '15 min',
    'text_20min': '20 min',
    'text_30min': '30 min',
    'text_45min': '45 min',
    'text_60min': '1 Stunde',
    'text_spcplay': 'SPC-Player',
    'text_spcload': 'Lade SPC in SPC700{127}{128}        ',
    'text_spcstarta': '**** Spiele SPC ****',
    'text_spcstartb': 'Name:  ',
    'text_spcstartc': 'Song:  ',
    'text_spcstartd': 'Artist:',
    'text_spc_statusbar': 'B:Zurueck',
    'text_loading': 'Lade{127}{128}                            ',
    'text_saving': 'Speichere{127}{128}                      ',
    'text_cheat': 'Cheats fuer ',
    'text_ips_nopatch': '[Kein Patch]',
    'cheat_tab_head': 'Name                                     Aktiv',
    'cheat_tab_hint_text': ' A:Ein/Aus   B:Speichern & Ende ',
    'mtext_browser_showcov': 'Cover anzeigen',
    'mdesc_browser_showcov': 'Spielcover im Menue anzeigen',
    'mtext_browser_covlists': ' {129}Favoriten/Letzte',
    'mdesc_browser_covlists': 'Cover auch in Letzte/Favoriten anzeigen',
    'mtext_browser_menumusic': 'Menue-Musik',
    'mtext_browser_menusfx': 'Menue-Sounds',
    'mdesc_browser_menumusic': 'Hintergrundmusik (menu.spc) im Menue spielen',
    'mtext_browser_restoretheme': 'Theme zuruecksetzen',
    'mdesc_browser_restoretheme': 'Menue-Theme auf Standard zuruecksetzen',
    'text_mm_language': 'Sprache',
    'mdesc_mm_language': 'Sprache fuer Menue/Firmware setzen',
}
