#!/usr/bin/env python3
# Bake the menu header logo (snes/logo.a65) from a 256x56 RGB image, encoded for
# CG DIRECT SELECT (Direct Color) mode.
#
#   python3 utils/bake_logo.py [source.png]      # default: gfx/logo256.png
#
# Sources shipped:  gfx/logo_fxpak.png  (FXPAK PRO, official),
#                   gfx/logo_sd2snes.png (the sd2snes "graffiti" logo).
#
# Why Direct Color: the OBJ cover art is forced by the hardware to use CGRAM
# 128..255, so a normal CGRAM-indexed logo and a cover fight over the palette
# (which is why the logo used to be cropped when a cover was shown). In Direct
# Color (BG1, Mode 3, register $2130 D0=1; SNES manual Book I ch.8 / p.A-17) the
# BG1 character data IS the colour and does NOT use CGRAM at all, so the whole
# CGRAM stays free for the cover. The full logo is then shown ALWAYS, the cover
# floats opaque (OBJ) over it, and the logo fills right up to the cover -- no gap,
# no colour conflict.
#
# Direct Color bit mapping (p.A-17): the 8bpp pixel byte DA is
#   bits[7:6]=Blue[1:0]  bits[5:3]=Green[2:0]  bits[2:0]=Red[2:0]   (the high bits)
# and the tilemap's 3 palette bits CL0/CL1/CL2 supply one extra LSB to R/G/B:
#   R5 = (DA[2:0]<<2) | (CL0<<1)   G5 = (DA[5:3]<<2) | (CL1<<1)   B5 = (DA[7:6]<<3) | (CL2<<2)
# So each 8x8 tile picks ONE 3-bit palette value as its R/G/B LSB nudge; that value
# goes in the BG1 tilemap entry (bits 10..12). DA==0 is TRANSPARENT (shows the dark
# menu backdrop): the logo's near-black areas encode to DA==0 and read as black,
# which matches a dark backdrop -- we do NOT nudge (nudging tints them, looks worse).
#
# Output snes/logo.a65:
#   logo_pal     - 64B placeholder so the _GFXPTR_ slot-1 label resolves (unused).
#   logo_charmap - 224 words: per cell (row*32+col) the BG1 tilemap entry =
#                  (pal3<<10) | (COVER_LOGO_CHAR + tile_index).
#   logo_tiles   - deduped 8bpp Direct-Color tiles.

import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_PNG = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "gfx", "logo256.png")
OUT_A65 = os.path.join(ROOT, "snes", "logo.a65")

COLS, ROWS = 32, 7
LOGO_CHAR = 0x300          # COVER_LOGO_CHAR (BG1 char of logo tile 0)


def to5(v):
    return v * 31 // 255


def encode_tile(px):
    t = [0]*64
    for r in range(8):
        for c in range(8):
            bit = 7 - c
            v = px[r][c]
            for p in range(8):
                if (v >> p) & 1:
                    base = (0, 16, 32, 48)[p // 2]
                    t[base + r*2 + (p % 2)] |= 1 << bit
    return bytes(t)


def da_of(R, G, B):
    """Top bits of (R,G,B 0..31) packed as the Direct-Color pixel byte."""
    return ((B >> 3) << 6) | ((G >> 2) << 3) | (R >> 2)


def best_pal3(tile_rgb):
    """Choose the 3-bit palette (CL2 CL1 CL0) minimising the per-tile error."""
    best, bestd = 0, 1 << 30
    for p3 in range(8):
        cr, cg, cb = p3 & 1, (p3 >> 1) & 1, (p3 >> 2) & 1
        d = 0
        for (R, G, B) in tile_rgb:
            R5 = ((R >> 2) << 2) | (cr << 1)
            G5 = ((G >> 2) << 2) | (cg << 1)
            B5 = ((B >> 3) << 3) | (cb << 2)
            d += (R5-R)**2 + (G5-G)**2 + (B5-B)**2
        if d < bestd:
            bestd, best = d, p3
    return best


def emit(label, data):
    out = [label]
    for i in range(0, len(data), 16):
        out.append("  .byt " + ",".join("$%02x" % b for b in data[i:i+16]))
    return "\n".join(out)


def main():
    img = Image.open(SRC_PNG).convert("RGB")
    if img.size != (COLS*8, ROWS*8):
        img = img.resize((COLS*8, ROWS*8), Image.LANCZOS)
    px = img.load()

    uniq, index = [], {}
    cellmap, palmap, transp = [], [], 0
    for ti in range(COLS*ROWS):
        cy, cx = divmod(ti, COLS)
        tile_rgb = [tuple(to5(v) for v in px[cx*8+c, cy*8+r])
                    for r in range(8) for c in range(8)]
        p3 = best_pal3(tile_rgb)
        da = [[0]*8 for _ in range(8)]
        k = 0
        for r in range(8):
            for c in range(8):
                R, G, B = tile_rgb[k]; k += 1
                d = da_of(R, G, B)        # DA==0 (near-black) -> transparent backdrop
                if d == 0:
                    transp += 1
                da[r][c] = d
        key = encode_tile(da)
        if key not in index:
            index[key] = len(uniq)
            uniq.append(key)
        cellmap.append(index[key])
        palmap.append(p3)

    if len(uniq) > 0x400 - LOGO_CHAR:      # char field is 10-bit
        sys.exit("too many unique tiles: %d" % len(uniq))
    tile_bytes = b"".join(uniq)

    charmap = bytearray()
    for cell in range(COLS*ROWS):
        entry = (palmap[cell] << 10) | (LOGO_CHAR + cellmap[cell])
        charmap += bytes([entry & 0xff, (entry >> 8) & 0xff])

    text = (
        "; AUTO-GENERATED by utils/bake_logo.py from %s - do not edit.\n"
        "; 32x7 logo (256x56px) in CG DIRECT SELECT (Direct Color): BG1 char data IS\n"
        "; the colour, no CGRAM used (cover OBJ owns CGRAM -> no conflict, no crop).\n"
        "; Enable with $2130 D0=1 in the Mode-3 header. logo_charmap = per-cell BG1\n"
        "; tilemap word (pal3<<10 | char); logo_pal is an unused _GFXPTR_ placeholder.\n"
        "; logo_tiles = %d bytes (%d unique tiles)  ->  COVER_LOGO_TILEBYTES.\n"
        ".link page $c0\n\n"
        % (os.path.basename(SRC_PNG), len(tile_bytes), len(uniq))
        + emit("logo_pal", bytes(64)) + "\n\n"
        + emit("logo_charmap", bytes(charmap)) + "\n\n"
        + emit("logo_tiles", tile_bytes) + "\n"
    )
    open(OUT_A65, "w").write(text)
    print("wrote %s from %s: logo_tiles=%d bytes (%d unique of %d cells), "
          "transparent(DA=0) px=%d, COVER_LOGO_TILEBYTES = $%04X"
          % (OUT_A65, os.path.basename(SRC_PNG), len(tile_bytes), len(uniq),
             COLS*ROWS, transp, len(tile_bytes)))


if __name__ == "__main__":
    main()
