CORE = sms

VSRC = address.v cheat.v clk_test.v ctx.v dac.v dcm.v dma.v bsx.v rtc.v srtc.v main.v mcu_cmd.v msu.v sd_dma.v spi.v sms_core.v sms.v sms_translate.v tv80/tv80s_ce.v tv80/tv80_core.v tv80/tv80_alu.v tv80/tv80_mcode.v tv80/tv80_reg.v
VHSRC =

COMMON_IP = dac_buf msu_databuf snescmd_buf

HEADER = config.vh

XIL_IP =
XIL_IPCORE_DIR = ip/mk2

INT_IP = pll

include ../settings.mk
include ../common.mk
