/* sd2snes - SD card based universal cartridge for the SNES
   patchmeta.h: per-ROM patch metadata sidecar (/sd2snes/patches/<BB>/<stem>.yml)

   An IPS carries no information about the base ROM it was authored against, so
   the copier-header convention is ultimately a user decision.  This sidecar is
   where that decision (and an optional friendlier display name) is remembered
   between boots.

   Layout: ONE yml per ROM, not per patch -- built with path_asset() so it lands
   in the same bucketed shape as saves/cheats/info/states and never pollutes the
   user's game folders.  A whole ROM's metadata is then one file open instead of
   one per patch, which matters because yaml.c can only hold a single file open.

     /sd2snes/patches/ZE/Zelda no Densetsu.yml
     ---
     # Generated by sd2snes
     - Patch: "Zelda no Densetsu_PT-BR.ips"
       Name: "Traducao PT-BR v1.2"
       Header: headered

   The DIRECTORY SCAN is the sole source of truth for which patches exist; this
   file is only an overlay keyed by patch basename.  An entry whose file is gone
   is ignored on read and dropped on the next write, so the sidecar heals itself
   the same way cfg_validity_check_listed_games heals recents/favorites.

   INVARIANT: yaml.c keeps a single global parser state, so none of these may be
   called from inside load_rom()/init(), where cheat_yaml_load() owns it. */

#ifndef __PATCHMETA_H
#define __PATCHMETA_H

#include <stdint.h>
#include "patch.h"

#define PATCH_BASEDIR ("/sd2snes/patches/")

/* Overlay the sidecar onto a freshly scanned list.  Reads Header: into the staged
   flags byte and writes a Name: override straight into the staged display slot at
   sram_addr, so no per-entry name buffer has to be kept around.  The scan itself
   is reached through patch_basename_at(), not through an array parameter -- the
   entries live in PSRAM (see patch.h).
   Silently does nothing when there is no sidecar (the normal case).
   Returns 1 if a sidecar was read, 0 otherwise. */
int patchmeta_apply(const uint8_t *rom_path, uint32_t sram_addr, uint8_t count);

/* Rewrite the sidecar from the live scan, pruning entries whose files are gone.
   Deletes the file outright when nothing is worth remembering (every patch on
   AUTO with no Name: of its own) so browsing a card does not litter it with
   empty ymls.  Name: overrides already in the file are preserved, but NORMALISED
   to the 41-character display width: the staged slots are the only live copy, so
   a hand-authored Name: longer than a menu row can show comes back shortened.
   See the note at the truncation in patchmeta_apply for why it is not round-tripped
   verbatim (single ystate global vs. the write path's stack). */
void patchmeta_save(const uint8_t *rom_path, uint32_t sram_addr, uint8_t count);

/* Flags byte for a single patch, for the recents/favorites relaunch path where
   no directory scan happens.  patch_type is PATCH_TYPE_IPS/PATCH_TYPE_BPS.
   Returns patch_type alone when there is no sidecar entry. */
uint8_t patchmeta_flags_for(const uint8_t *rom_path, const char *patch_basename,
                            uint8_t patch_type);

#endif /* __PATCHMETA_H */
